Attribute VB_Name = "srvrAppe"
'---------------------------------------------------------
Option Explicit
'---------------------------------------------------------

Public Const constrIntv = "rAppe"

Type typerAppe
    
    Aid                            As Integer                  ' SAA identification
    appe_s_umidl                   As Long                     ' Left part of the internal Swift message reference message)
    appe_s_umidh                   As Long                     ' Right part of the internal Swift message reference
    appe_inst_num                  As Long                     ' Instance index for the message (0=original instance)
    appe_date_time                 As Date                     ' Creation date and time of the appendix
    appe_seq_nbr                   As Double '$JPL 2007-01-09 Long                   ' Sequence number to make combination unique on top of date/time in a key
    
    appe_iapp_name                 As String '* 32              ' Type of network that sends/receives the message : APPLI - SWIFT - TELEX
    appe_type                      As String '* 32              ' APPE_EMISSION or APPE_RECEPTION
    appe_session_holder            As String '* 32              ' Element name which established the session during message transmission
    appe_session_nbr               As Double '$JPL 2007-01-09 Long                     ' Session number assigned to a network session
    appe_sequence_nbr              As Double '$JPL 2007-01-09 Long                     ' Sequence number for a message network transmission
    appe_transmission_nbr          As Double '$JPL 2007-01-09 Long                 ' This field makes a unique secondary key
    appe_crea_appl_serv_name       As String '* 32              ' Application name that created the appendix
    appe_crea_mpfn_name            As String '* 32              ' Name of the function that created the appendix
    appe_crea_rp_name              As String '* 32              ' Queue name in which the message instance stayed while the appendix was created
    appe_data_last                 As Long                     ' Length of the encapsulated field
    appe_token                     As Long                     ' CRC on the appendix (generated by SAA)
    appe_ack_nack_text             As String '* 255             ' Network acknowledgement text. For Swift, it is ACK or NACK text
    appe_answerback                As String '* 32              ' Answerback to be used on the Telex line
    appe_auth_result               As String '* 32              ' Values indicates the success of applying the authentification process to a message
    appe_auth_value                As String '* 41              ' Emission or Reception authenticator
    appe_carrier_acceptance_id     As String '* 32              ' Message acceptance identifier
    appe_checksum_result           As String '* 32              ' Result code of the checksum validation process
    appe_checksum_value            As String '* 32              ' Checksum of a message
    appe_conn_response_code        As String '* 32              '
    appe_conn_response_text        As String '* 32              '
    appe_crest_com_server_id       As String '* 32              '
    appe_crest_gateway_id          As String '* 32              '
    appe_cui                       As String '* 32              ' Call unit identifier
    appe_fax_batch_sequence        As String '* 32              '
    appe_fax_duration              As String '* 32              ' Fax transmission in seconds
    appe_fax_number                As String '* 32              ' Fax number that was used
    appe_fax_tnap_name             As String '* 32              ' Name used to refer to the network application
    appe_local_output_time         As Date                     ' Time when the message was received by SAA from Swift
    appe_nak_reason                As String '* 32              ' The NACK reason code
    appe_network_delivery_status   As String '* 32              ' Delivery status of the message to the network (not to the receiver!)
    appe_pac_result                As String '* 32              ' Proprietary authentication values (for PREMIUM)
    appe_pac_value                 As String '* 41              ' Value of the emission or reception PAC
    appe_rcv_delivery_status       As String '* 32              ' Delivery status to the receiver
    appe_remote_input_reference    As String '* 32              ' Network generated reference when the message was sent at the remote site
    appe_remote_input_time         As Date                     ' Time at which the message was input to the network at the remote site
    appe_sender_cancel_status      As String '* 32              ' Sender cancellation status
    appe_telex_batch_sequence      As String '* 32              '
    appe_telex_duration            As String '* 32              ' Telex duration in seconds
    appe_telex_number              As String '* 32              ' Telex number that was used
    appe_tnap_name                 As String '* 32              ' Name used to refer to the network application
    x_appe_last                    As Integer                  ' Flag set to 1 when the appendix is the last one for that message

End Type

'---------------------------------------------------------
Public Function srvrAppe_GetBuffer_ODBC(rsADO As ADODB.Recordset, recrAppe As typerAppe)
'---------------------------------------------------------
On Error GoTo Error_Handler
srvrAppe_GetBuffer_ODBC = Null

recrAppe.Aid = rsADO("Aid")
recrAppe.appe_s_umidl = rsADO("appe_s_umidl")
recrAppe.appe_s_umidh = rsADO("appe_s_umidh")
recrAppe.appe_inst_num = rsADO("appe_inst_num")
recrAppe.appe_date_time = rsADO("appe_date_time")
recrAppe.appe_seq_nbr = rsADO("appe_seq_nbr")

recrAppe.appe_iapp_name = rsADO("appe_iapp_name")
recrAppe.appe_type = rsADO("appe_type")
recrAppe.appe_session_holder = rsADO("appe_session_holder")
recrAppe.appe_session_nbr = rsADO("appe_session_nbr")
recrAppe.appe_sequence_nbr = rsADO("appe_sequence_nbr")
recrAppe.appe_transmission_nbr = rsADO("appe_transmission_nbr")
If IsNull(rsADO("appe_crea_appl_serv_name")) Then
    recrAppe.appe_crea_appl_serv_name = ""
Else
    recrAppe.appe_crea_appl_serv_name = rsADO("appe_crea_appl_serv_name")
End If
recrAppe.appe_crea_mpfn_name = rsADO("appe_crea_mpfn_name")
recrAppe.appe_crea_rp_name = rsADO("appe_crea_rp_name")
If IsNull(rsADO("appe_data_last")) Then
    recrAppe.appe_data_last = 0
Else
    recrAppe.appe_data_last = rsADO("appe_data_last")
End If
If IsNull(rsADO("appe_token")) Then
    recrAppe.appe_token = 0
Else
    recrAppe.appe_token = rsADO("appe_token")
End If
If IsNull(rsADO("appe_ack_nack_text")) Then
    recrAppe.appe_ack_nack_text = ""
Else
    recrAppe.appe_ack_nack_text = rsADO("appe_ack_nack_text")
End If
If IsNull(rsADO("appe_answerback")) Then
    recrAppe.appe_answerback = ""
Else
    recrAppe.appe_answerback = rsADO("appe_answerback")
End If
If IsNull(rsADO("appe_auth_result")) Then
    recrAppe.appe_auth_result = ""
Else
    recrAppe.appe_auth_result = rsADO("appe_auth_result")
End If
If IsNull(rsADO("appe_auth_value")) Then
    recrAppe.appe_auth_value = ""
Else
    recrAppe.appe_auth_value = rsADO("appe_auth_value")
End If
If IsNull(rsADO("appe_carrier_acceptance_id")) Then
    recrAppe.appe_carrier_acceptance_id = ""
Else
    recrAppe.appe_carrier_acceptance_id = rsADO("appe_carrier_acceptance_id")
End If
If IsNull(rsADO("appe_checksum_result")) Then
    recrAppe.appe_checksum_result = ""
Else
    recrAppe.appe_checksum_result = rsADO("appe_checksum_result")
End If
If IsNull(rsADO("appe_checksum_value")) Then
    recrAppe.appe_checksum_value = ""
Else
    recrAppe.appe_checksum_value = rsADO("appe_checksum_value")
End If
If IsNull(rsADO("appe_conn_response_code")) Then
    recrAppe.appe_conn_response_code = ""
Else
    recrAppe.appe_conn_response_code = rsADO("appe_conn_response_code")
End If
If IsNull(rsADO("appe_conn_response_text")) Then
    recrAppe.appe_conn_response_text = ""
Else
    recrAppe.appe_conn_response_text = rsADO("appe_conn_response_text")
End If
If IsNull(rsADO("appe_crest_com_server_id")) Then
    recrAppe.appe_crest_com_server_id = ""
Else
    recrAppe.appe_crest_com_server_id = rsADO("appe_crest_com_server_id")
End If
If IsNull(rsADO("appe_crest_gateway_id")) Then
    recrAppe.appe_crest_gateway_id = ""
Else
    recrAppe.appe_crest_gateway_id = rsADO("appe_crest_gateway_id")
End If
If IsNull(rsADO("appe_cui")) Then
    recrAppe.appe_cui = ""
Else
    recrAppe.appe_cui = rsADO("appe_cui")
End If
If IsNull(rsADO("appe_fax_batch_sequence")) Then
    recrAppe.appe_fax_batch_sequence = ""
Else
    recrAppe.appe_fax_batch_sequence = rsADO("appe_fax_batch_sequence")
End If
If IsNull(rsADO("appe_ack_nack_text")) Then
    recrAppe.appe_fax_duration = ""
Else
    recrAppe.appe_fax_duration = rsADO("appe_ack_nack_text")
End If
If IsNull(rsADO("appe_fax_number")) Then
    recrAppe.appe_fax_number = ""
Else
    recrAppe.appe_fax_number = rsADO("appe_fax_number")
End If
If IsNull(rsADO("appe_fax_tnap_name")) Then
    recrAppe.appe_fax_tnap_name = ""
Else
    recrAppe.appe_fax_tnap_name = rsADO("appe_fax_tnap_name")
End If
If IsNull(rsADO("appe_local_output_time")) Then
    recrAppe.appe_local_output_time = 0
Else
    recrAppe.appe_local_output_time = rsADO("appe_local_output_time")
End If
If IsNull(rsADO("appe_nak_reason")) Then
    recrAppe.appe_nak_reason = ""
Else
    recrAppe.appe_nak_reason = rsADO("appe_nak_reason")
End If
If IsNull(rsADO("appe_network_delivery_status")) Then
    recrAppe.appe_network_delivery_status = ""
Else
    recrAppe.appe_network_delivery_status = rsADO("appe_network_delivery_status")
End If
If IsNull(rsADO("appe_pac_result")) Then
    recrAppe.appe_pac_result = ""
Else
    recrAppe.appe_pac_result = rsADO("appe_pac_result")
End If
If IsNull(rsADO("appe_pac_value")) Then
    recrAppe.appe_pac_value = ""
Else
    recrAppe.appe_pac_value = rsADO("appe_pac_value")
End If
If IsNull(rsADO("appe_rcv_delivery_status")) Then
    recrAppe.appe_rcv_delivery_status = ""
Else
    recrAppe.appe_rcv_delivery_status = rsADO("appe_rcv_delivery_status")
End If
If IsNull(rsADO("appe_remote_input_reference")) Then
    recrAppe.appe_remote_input_reference = ""
Else
    recrAppe.appe_remote_input_reference = rsADO("appe_remote_input_reference")
End If
If IsNull(rsADO("appe_remote_input_time")) Then
    recrAppe.appe_remote_input_time = 0
Else
    recrAppe.appe_remote_input_time = rsADO("appe_remote_input_time")
End If
If IsNull(rsADO("appe_sender_cancel_status")) Then
    recrAppe.appe_sender_cancel_status = ""
Else
    recrAppe.appe_sender_cancel_status = rsADO("appe_sender_cancel_status")
End If
If IsNull(rsADO("appe_telex_batch_sequence")) Then
    recrAppe.appe_telex_batch_sequence = ""
Else
    recrAppe.appe_telex_batch_sequence = rsADO("appe_telex_batch_sequence")
End If
If IsNull(rsADO("appe_telex_duration")) Then
    recrAppe.appe_telex_duration = ""
Else
    recrAppe.appe_telex_duration = rsADO("appe_telex_duration")
End If
If IsNull(rsADO("appe_telex_number")) Then
    recrAppe.appe_telex_number = ""
Else
    recrAppe.appe_telex_number = rsADO("appe_telex_number")
End If
If IsNull(rsADO("appe_tnap_name")) Then
    recrAppe.appe_tnap_name = ""
Else
    recrAppe.appe_tnap_name = rsADO("appe_tnap_name")
End If

recrAppe.x_appe_last = rsADO("x_appe_last")

Exit Function

Error_Handler:
srvrAppe_GetBuffer_ODBC = Error

End Function

'---------------------------------------------------------
Public Sub srvrAppe_Init(recrAppe As typerAppe)
'---------------------------------------------------------

recrAppe.Aid = 0
recrAppe.appe_s_umidl = 0
recrAppe.appe_s_umidh = 0
recrAppe.appe_inst_num = 0
recrAppe.appe_date_time = 0
recrAppe.appe_seq_nbr = 0

recrAppe.appe_iapp_name = ""
recrAppe.appe_type = ""
recrAppe.appe_session_holder = ""
recrAppe.appe_session_nbr = 0
recrAppe.appe_sequence_nbr = 0
recrAppe.appe_transmission_nbr = 0
recrAppe.appe_crea_appl_serv_name = ""
recrAppe.appe_crea_mpfn_name = ""
recrAppe.appe_crea_rp_name = ""
recrAppe.appe_data_last = 0
recrAppe.appe_token = 0
recrAppe.appe_ack_nack_text = ""
recrAppe.appe_answerback = ""
recrAppe.appe_auth_result = ""
recrAppe.appe_auth_value = ""
recrAppe.appe_carrier_acceptance_id = ""
recrAppe.appe_checksum_result = ""
recrAppe.appe_checksum_value = ""
recrAppe.appe_conn_response_code = ""
recrAppe.appe_conn_response_text = ""
recrAppe.appe_crest_com_server_id = ""
recrAppe.appe_crest_gateway_id = ""
recrAppe.appe_cui = ""
recrAppe.appe_fax_batch_sequence = ""
recrAppe.appe_fax_duration = ""
recrAppe.appe_fax_number = ""
recrAppe.appe_fax_tnap_name = ""
recrAppe.appe_local_output_time = 0
recrAppe.appe_nak_reason = ""
recrAppe.appe_network_delivery_status = ""
recrAppe.appe_pac_result = ""
recrAppe.appe_pac_value = ""
recrAppe.appe_rcv_delivery_status = ""
recrAppe.appe_remote_input_reference = ""
recrAppe.appe_remote_input_time = 0
recrAppe.appe_sender_cancel_status = ""
recrAppe.appe_telex_batch_sequence = ""
recrAppe.appe_telex_duration = ""
recrAppe.appe_telex_number = ""
recrAppe.appe_tnap_name = ""
recrAppe.x_appe_last = 0

End Sub

'---------------------------------------------------------
Public Sub srvrAppe_ElpDisplay(recrAppe As typerAppe)
'---------------------------------------------------------
''frmElpDisplay.fgData.Rows = 48

''frmElpDisplay.fgData.Row = 1
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "Aid"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.Aid

''frmElpDisplay.fgData.Row = 2
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_s_umidl"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_s_umidl

''frmElpDisplay.fgData.Row = 3
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_s_umidh"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_s_umidh

''frmElpDisplay.fgData.Row = 4
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_inst_num"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_inst_num

''frmElpDisplay.fgData.Row = 5
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_date_time"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_date_time

''frmElpDisplay.fgData.Row = 6
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_seq_nbr"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_seq_nbr

''frmElpDisplay.fgData.Row = 7
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_iapp_name"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_iapp_name
''frmElpDisplay.fgData.Row = 8
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_type"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_type

''frmElpDisplay.fgData.Row = 9
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_session_holder"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_session_holder

''frmElpDisplay.fgData.Row = 10
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_session_nbr"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_session_nbr

''frmElpDisplay.fgData.Row = 11
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_sequence_nbr"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_sequence_nbr

''frmElpDisplay.fgData.Row = 12
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_transmission_nbr"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_transmission_nbr

''frmElpDisplay.fgData.Row = 13
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_crea_appl_serv_name"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_crea_appl_serv_name

''frmElpDisplay.fgData.Row = 14
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_crea_mpfn_name"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_crea_mpfn_name

''frmElpDisplay.fgData.Row = 15
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_crea_rp_name"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_crea_rp_name

''frmElpDisplay.fgData.Row = 16
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_data_last"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_data_last

''frmElpDisplay.fgData.Row = 17
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_token"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_token

''frmElpDisplay.fgData.Row = 18
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_ack_nack_text"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_ack_nack_text

''frmElpDisplay.fgData.Row = 19
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_answerback"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_answerback

''frmElpDisplay.fgData.Row = 20
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_auth_result"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_auth_result

''frmElpDisplay.fgData.Row = 21
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_auth_value"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_auth_value

''frmElpDisplay.fgData.Row = 22
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_carrier_acceptance_id"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_carrier_acceptance_id

''frmElpDisplay.fgData.Row = 23
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_checksum_result"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_checksum_result

''frmElpDisplay.fgData.Row = 24
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_checksum_value"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_checksum_value

''frmElpDisplay.fgData.Row = 25
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_conn_response_code"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_conn_response_code

''frmElpDisplay.fgData.Row = 26
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_conn_response_text"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_conn_response_text

''frmElpDisplay.fgData.Row = 27
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_crest_com_server_id"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_crest_com_server_id

''frmElpDisplay.fgData.Row = 28
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_crest_gateway_id"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_crest_gateway_id

''frmElpDisplay.fgData.Row = 29
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_cui"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_cui

''frmElpDisplay.fgData.Row = 30
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_fax_batch_sequence"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_fax_batch_sequence

''frmElpDisplay.fgData.Row = 31
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_fax_duration"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_fax_duration

''frmElpDisplay.fgData.Row = 32
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_fax_number"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_fax_number

''frmElpDisplay.fgData.Row = 33
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_fax_tnap_name"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_fax_tnap_name

''frmElpDisplay.fgData.Row = 34
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_local_output_time"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_local_output_time

''frmElpDisplay.fgData.Row = 35
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_nak_reason"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_nak_reason

''frmElpDisplay.fgData.Row = 36
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_network_delivery_status"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_network_delivery_status

''frmElpDisplay.fgData.Row = 37
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_pac_result"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_pac_result

''frmElpDisplay.fgData.Row = 38
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_pac_value"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_pac_value

''frmElpDisplay.fgData.Row = 39
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_rcv_delivery_status"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_rcv_delivery_status

''frmElpDisplay.fgData.Row = 40
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_remote_input_reference"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_remote_input_reference

''frmElpDisplay.fgData.Row = 41
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_remote_input_time"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_remote_input_time

''frmElpDisplay.fgData.Row = 42
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_sender_cancel_status"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_sender_cancel_status

''frmElpDisplay.fgData.Row = 43
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_telex_batch_sequence"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_telex_batch_sequence

''frmElpDisplay.fgData.Row = 44
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_telex_duration"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_telex_duration

''frmElpDisplay.fgData.Row = 45
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_telex_number"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_telex_number

''frmElpDisplay.fgData.Row = 46
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "appe_tnap_name"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.appe_tnap_name

''frmElpDisplay.fgData.Row = 47
''frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_appe_last"
''frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
''frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrAppe.x_appe_last

MsgBox "à faire : frmElpDisplay.Show ", vbCritical '  vbModal

End Sub






