Attribute VB_Name = "srvrInst"
'---------------------------------------------------------
Option Explicit
'---------------------------------------------------------

Public Const constrInst = "rInst"

Type typerInst
    
    Aid                            As Integer                  ' SAA identification
    inst_s_umidl                   As Long                     ' Left part of the internal Swift message reference
    inst_s_umidh                   As Long                     ' Right part of the internal Swift message reference
    inst_num                       As Long                     ' Index of the instance for that message - 0=Original
    
    inst_type                      As String '* 32              ' Type of instance : ORIGINAL - COPY - NOTIFICATION
    inst_notification_type         As String '* 32              ' A NOTIFICATION instance contains information about another message instance
    inst_status                    As String '* 24              ' Status (Live or Complete) of that message instance
    inst_related_nbr               As Double '$JPL 2007-01-09 Long                  ' This field is only for notification and copy instances
    inst_appe_date_time            As Date                     ' Creation date and time of the related appendix (for notification of transmission instances)
    inst_appe_seq_nbr              As Double '$JPL 2007-01-09 Long                 ' Qequence numnber of the related appendix (for notification of transmission instances)
    inst_unit_name                 As String '* 32              ' Unit to which the instance belongs
    inst_rp_name                   As String '* 24              ' Queue in which the instance resides
    inst_mpfn_name                 As String '* 24              ' Name of the last SAA function that processed the message instance
    inst_mpfn_handle               As String '* 46              ' Handle to recognize physical MPFN instance
    inst_process_state             As Integer                  ' Application processing state for message instance
    inst_last_mpfn_result          As String '* 16              ' Code of the last MPFN result for the message instance
    inst_relative_ref              As Long                     ' Position of the message instance in a queue
    inst_sm2000_priority           As Integer                  ' general priority of a message in sm2000
    inst_deferred_time             As Date                     ' Time when a message needs to be sent
    inst_crea_appl_serv_name       As String '* 24              ' Name of the application that created the instance
    inst_crea_mpfn_name            As String '* 24              ' Name of the message processing function that created the message
    inst_crea_rp_name              As String '* 24              ' Queue in which the instance has been put after being created
    inst_crea_date_time            As Date                     ' Instance creation date and time
    initial_target_rp_name         As String '* 24              '
    inst_auth_oper_nickname        As String '* 11              ' Short name of the operator that authorized this instance
    inst_last_oper_nickname        As String '* 11              ' Short name of the last operator that manipulated the message
    inst_data_last                 As Long                      '
    inst_token                     As Long                     ' CRC on the message (generated by SAA)
    inst_answerback                As String '* 32              ' Answerback of the receiver TELEX correspondent
    inst_appli_rp_name             As String '* 32              ' Name of the instance exit point through which the instance passed
    inst_calc_description          As String '* 32              ' Free format description to be displayed in scrolled text window
    inst_calculated_testkey_value  As String '* 32              ' Testkey calculted on a sent TELEX
    inst_computation_details       As String '* 512             ' Details about the computation of the testkey
    inst_corr_X1                   As String '* 32              '
    inst_corr_X2                   As String '* 32              '
    inst_crest_com_server_id       As String '* 32              '
    inst_crest_gateway_id          As String '* 32              '
    inst_extracted_testkey_value   As String '* 32              ' Extracted testkey value on a received TELEX
    inst_fax_cui                   As String '* 32              ' FAX Call Unit Identifier
    inst_fax_number                As String '* 32              ' FAX number
    inst_fax_origin                As String '* 32              ' Origin of FAX Address
    inst_fax_tnap_name             As String '* 32              ' Name used to refer to the network application identifier for FAXES
    inst_letter_coding             As String '* 32              ' Contribution for letter coding method
    inst_rcv_delivery_status       As String '* 32              ' Status of delivery to receiver  (no to SWIFT)
    inst_receiver_X1               As String '* 11              ' BIC 11 of the message receiver
    inst_receiver_X2               As String '* 21              ' Department name of the message receiver
    inst_receiver_X3               As String '* 21              ' Last name of the message receiver
    inst_receiver_X4               As String '* 21              ' First name of the message receiver
    inst_receiver_branch_info      As String '* 71              ' Name of the branch that will receive the message
    inst_receiver_city_name        As String '* 36              ' City of the receiver
    inst_receiver_corr_type        As String '* 21              ' Type of receiver correspondent
    inst_receiver_ctry_code        As String '* 3               ' Country code of the receiver
    inst_receiver_ctry_name        As String '* 71              ' Country name of the receiver
    inst_receiver_institution_name As String '* 106             ' Institution name of the receiver
    inst_receiver_location         As String '* 106             ' Location of the receiver
    inst_receiver_network_iapp_name As String '* 21              '
    inst_receiver_secu_iapp_name   As String '* 32              '
    inst_retry_count               As Long                      ' Retry count within the current retry cycle when sending a message
    inst_retry_cycle               As Long                      ' Retry cycle number when sending a message
    inst_routing_code              As String '* 17              ' Free format test to influence routing
    inst_telex_number              As String '* 32              ' Telex number to use when sending a Telex
    inst_telex_origin              As String '* 32              ' Origin of the Telex
    inst_test_comment              As String '* 32              '
    inst_test_date_time            As Date                      '
    inst_test_system               As String '* 32              '
    inst_testkey_required          As String '* 32              '
    inst_testkey_status            As String '* 32              '
    inst_tnap_name                 As String '* 32              ' Name used to refer to the network application identifier for TELEX
    x_last_emi_appe_date_time      As Date                      ' Date
    x_last_emi_appe_seq_nbr        As Double '$JPL 2007-01-09 Long                      '
    x_last_rec_appe_date_time      As Date                      '
    x_last_rec_appe_seq_nbr        As Double '$JPL 2007-01-09 Long                    '
    inst_oper_comment              As String '* 501             ' Comments entered by operators about this instance
    inst_va41_audi_seq_nbr         As Double '$JPL 2007-01-09 Long                    '
    inst_va41_awb_check_text_result As String '* 20             '
    inst_va41_calcul_date_time     As Date                      '
    inst_va41_contains_unscissored_part As Integer              '
    inst_va41_testkey_calculated   As Integer                   '

End Type


'---------------------------------------------------------
Public Function srvrInst_GetBuffer_ODBC(rsAdo As ADODB.Recordset, recrInst As typerInst)
'---------------------------------------------------------
On Error GoTo Error_Handler
srvrInst_GetBuffer_ODBC = Null

recrInst.Aid = rsAdo("Aid")
recrInst.inst_s_umidl = rsAdo("inst_s_umidl")
recrInst.inst_s_umidh = rsAdo("inst_s_umidh")
recrInst.inst_num = rsAdo("inst_num")
recrInst.inst_type = rsAdo("inst_type")
recrInst.inst_notification_type = rsAdo("inst_notification_type")
recrInst.inst_status = rsAdo("inst_status")
recrInst.inst_related_nbr = rsAdo("inst_related_nbr")
recrInst.inst_appe_date_time = rsAdo("inst_appe_date_time")
recrInst.inst_appe_seq_nbr = rsAdo("inst_appe_seq_nbr")
recrInst.inst_unit_name = rsAdo("inst_unit_name")
If IsNull(rsAdo("inst_rp_name")) Then
    recrInst.inst_rp_name = ""
Else
    recrInst.inst_rp_name = rsAdo("inst_rp_name")

End If
recrInst.inst_mpfn_name = rsAdo("inst_mpfn_name")
If IsNull(rsAdo("inst_mpfn_handle")) Then
    recrInst.inst_mpfn_handle = ""
Else
    recrInst.inst_mpfn_handle = rsAdo("inst_mpfn_handle")
End If
recrInst.inst_process_state = rsAdo("inst_process_state")
recrInst.inst_last_mpfn_result = rsAdo("inst_last_mpfn_result")
recrInst.inst_relative_ref = rsAdo("inst_relative_ref")
recrInst.inst_sm2000_priority = rsAdo("inst_sm2000_priority")
recrInst.inst_deferred_time = rsAdo("inst_deferred_time")
If IsNull(rsAdo("inst_crea_appl_serv_name")) Then
    recrInst.inst_crea_appl_serv_name = ""
Else
    recrInst.inst_crea_appl_serv_name = rsAdo("inst_crea_appl_serv_name")
End If
recrInst.inst_crea_mpfn_name = rsAdo("inst_crea_mpfn_name")
recrInst.inst_crea_rp_name = rsAdo("inst_crea_rp_name")
recrInst.inst_crea_date_time = rsAdo("inst_crea_date_time")
If IsNull(rsAdo("initial_target_rp_name")) Then
    recrInst.initial_target_rp_name = ""
Else
    recrInst.initial_target_rp_name = rsAdo("initial_target_rp_name")
End If
If IsNull(rsAdo("inst_auth_oper_nickname")) Then
    recrInst.inst_auth_oper_nickname = ""
Else
    recrInst.inst_auth_oper_nickname = rsAdo("inst_auth_oper_nickname")
End If
If IsNull(rsAdo("inst_last_oper_nickname")) Then
    recrInst.inst_last_oper_nickname = ""
Else
    recrInst.inst_last_oper_nickname = rsAdo("inst_last_oper_nickname")
End If
If IsNull(rsAdo("inst_data_last")) Then
    recrInst.inst_data_last = 0
Else
    recrInst.inst_data_last = rsAdo("inst_data_last")
End If
If IsNull(rsAdo("inst_token")) Then
    recrInst.inst_token = 0
Else
    recrInst.inst_token = rsAdo("inst_token")
End If
If IsNull(rsAdo("inst_answerback")) Then
    recrInst.inst_answerback = ""
Else
    recrInst.inst_answerback = rsAdo("inst_answerback")
End If
If IsNull(rsAdo("inst_appli_rp_name")) Then
    recrInst.inst_appli_rp_name = ""
Else
    recrInst.inst_appli_rp_name = rsAdo("inst_appli_rp_name")
End If
If IsNull(rsAdo("inst_calc_description")) Then
    recrInst.inst_calc_description = ""
Else
    recrInst.inst_calc_description = rsAdo("inst_calc_description")
End If
If IsNull(rsAdo("inst_calculated_testkey_value")) Then
    recrInst.inst_calculated_testkey_value = ""
Else
    recrInst.inst_calculated_testkey_value = rsAdo("inst_calculated_testkey_value")
End If
If IsNull(rsAdo("inst_computation_details")) Then
    recrInst.inst_computation_details = ""
Else
    recrInst.inst_computation_details = rsAdo("inst_computation_details")
End If
If IsNull(rsAdo("inst_corr_X1")) Then
    recrInst.inst_corr_X1 = ""
Else
    recrInst.inst_corr_X1 = rsAdo("inst_corr_X1")
End If
If IsNull(rsAdo("inst_corr_X2")) Then
    recrInst.inst_corr_X2 = ""
Else
    recrInst.inst_corr_X2 = rsAdo("inst_corr_X2")
End If
If IsNull(rsAdo("inst_crest_com_server_id")) Then
    recrInst.inst_crest_com_server_id = ""
Else
    recrInst.inst_crest_com_server_id = rsAdo("inst_crest_com_server_id")
End If
If IsNull(rsAdo("inst_crest_gateway_id")) Then
    recrInst.inst_crest_gateway_id = ""
Else
    recrInst.inst_crest_gateway_id = rsAdo("inst_crest_gateway_id")
End If
If IsNull(rsAdo("inst_extracted_testkey_value")) Then
    recrInst.inst_extracted_testkey_value = ""
Else
    recrInst.inst_extracted_testkey_value = rsAdo("inst_extracted_testkey_value")
End If
If IsNull(rsAdo("inst_fax_cui")) Then
    recrInst.inst_fax_cui = ""
Else
    recrInst.inst_fax_cui = rsAdo("inst_fax_cui")
End If
If IsNull(rsAdo("inst_fax_number")) Then
    recrInst.inst_fax_number = ""
Else
    recrInst.inst_fax_number = rsAdo("inst_fax_number")
End If
If IsNull(rsAdo("inst_fax_origin")) Then
    recrInst.inst_fax_origin = ""
Else
    recrInst.inst_fax_origin = rsAdo("inst_fax_origin")
End If
If IsNull(rsAdo("inst_fax_tnap_name")) Then
    recrInst.inst_fax_tnap_name = ""
Else
    recrInst.inst_fax_tnap_name = rsAdo("inst_fax_tnap_name")
End If
If IsNull(rsAdo("inst_letter_coding")) Then
    recrInst.inst_letter_coding = ""
Else
    recrInst.inst_letter_coding = rsAdo("inst_letter_coding")
End If
If IsNull(rsAdo("inst_rcv_delivery_status")) Then
    recrInst.inst_rcv_delivery_status = ""
Else
    recrInst.inst_rcv_delivery_status = rsAdo("inst_rcv_delivery_status")
End If
If IsNull(rsAdo("inst_receiver_X1")) Then
    recrInst.inst_receiver_X1 = ""
Else
    recrInst.inst_receiver_X1 = rsAdo("inst_receiver_X1")
End If
If IsNull(rsAdo("inst_receiver_X2")) Then
    recrInst.inst_receiver_X2 = ""
Else
    recrInst.inst_receiver_X2 = rsAdo("inst_receiver_X2")
End If
If IsNull(rsAdo("inst_receiver_X3")) Then
    recrInst.inst_receiver_X3 = ""
Else
    recrInst.inst_receiver_X3 = rsAdo("inst_receiver_X3")
End If
If IsNull(rsAdo("inst_receiver_X4")) Then
    recrInst.inst_receiver_X4 = ""
Else
    recrInst.inst_receiver_X4 = rsAdo("inst_receiver_X4")
End If
If IsNull(rsAdo("inst_receiver_branch_info")) Then
    recrInst.inst_receiver_branch_info = ""
Else
    recrInst.inst_receiver_branch_info = rsAdo("inst_receiver_branch_info")
End If
If IsNull(rsAdo("inst_receiver_city_name")) Then
    recrInst.inst_receiver_city_name = ""
Else
    recrInst.inst_receiver_city_name = rsAdo("inst_receiver_city_name")
End If
If IsNull(rsAdo("inst_receiver_corr_type")) Then
    recrInst.inst_receiver_corr_type = ""
Else
    recrInst.inst_receiver_corr_type = rsAdo("inst_receiver_corr_type")
End If
If IsNull(rsAdo("inst_receiver_ctry_code")) Then
    recrInst.inst_receiver_ctry_code = ""
Else
    recrInst.inst_receiver_ctry_code = rsAdo("inst_receiver_ctry_code")
End If
If IsNull(rsAdo("inst_receiver_ctry_name")) Then
    recrInst.inst_receiver_ctry_name = ""
Else
    recrInst.inst_receiver_ctry_name = rsAdo("inst_receiver_ctry_name")
End If
If IsNull(rsAdo("inst_receiver_institution_name")) Then
    recrInst.inst_receiver_institution_name = ""
Else
    recrInst.inst_receiver_institution_name = rsAdo("inst_receiver_institution_name")
End If
If IsNull(rsAdo("inst_receiver_location")) Then
    recrInst.inst_receiver_location = ""
Else
    recrInst.inst_receiver_location = rsAdo("inst_receiver_location")
End If
'$20070530 JPL  If IsNull(rsado("inst_receiver_network_iapp_name")) Then
'$20070530 JPL     recrInst.inst_receiver_network_iapp_name = ""
'$20070530 JPL Else
'$20070530 JPL     recrInst.inst_receiver_network_iapp_name = rsado("inst_receiver_network_iapp_name")
'$20070530 JPL End If

If IsNull(rsAdo("inst_receiver_secu_iapp_name")) Then
    recrInst.inst_receiver_secu_iapp_name = ""
Else
    recrInst.inst_receiver_secu_iapp_name = rsAdo("inst_receiver_secu_iapp_name")
End If
If IsNull(rsAdo("inst_retry_count")) Then
    recrInst.inst_retry_count = 0
Else
    recrInst.inst_retry_count = rsAdo("inst_retry_count")
End If
If IsNull(rsAdo("inst_retry_cycle")) Then
    recrInst.inst_retry_cycle = 0
Else
    recrInst.inst_retry_cycle = rsAdo("inst_retry_cycle")
End If
If IsNull(rsAdo("inst_routing_code")) Then
    recrInst.inst_routing_code = ""
Else
    recrInst.inst_routing_code = rsAdo("inst_routing_code")
End If
If IsNull(rsAdo("inst_telex_number")) Then
    recrInst.inst_telex_number = ""
Else
    recrInst.inst_telex_number = rsAdo("inst_telex_number")
End If
If IsNull(rsAdo("inst_telex_origin")) Then
    recrInst.inst_telex_origin = ""
Else
    recrInst.inst_telex_origin = rsAdo("inst_telex_origin")
End If
If IsNull(rsAdo("inst_test_comment")) Then
    recrInst.inst_test_comment = ""
Else
    recrInst.inst_test_comment = rsAdo("inst_test_comment")
End If
If IsNull(rsAdo("inst_test_date_time")) Then
    recrInst.inst_test_date_time = 0
Else
    recrInst.inst_test_date_time = rsAdo("inst_test_date_time")
End If
If IsNull(rsAdo("inst_test_system")) Then
    recrInst.inst_test_system = ""
Else
    recrInst.inst_test_system = rsAdo("inst_test_system")
End If
If IsNull(rsAdo("inst_testkey_required")) Then
    recrInst.inst_testkey_required = ""
Else
    recrInst.inst_testkey_required = rsAdo("inst_testkey_required")
End If
If IsNull(rsAdo("inst_testkey_status")) Then
    recrInst.inst_testkey_status = ""
Else
    recrInst.inst_testkey_status = rsAdo("inst_testkey_status")
End If
If IsNull(rsAdo("inst_tnap_name")) Then
    recrInst.inst_tnap_name = ""
Else
    recrInst.inst_tnap_name = rsAdo("inst_tnap_name")
End If
If IsNull(rsAdo("x_last_emi_appe_date_time")) Then
    recrInst.x_last_emi_appe_date_time = 0
Else
    recrInst.x_last_emi_appe_date_time = rsAdo("x_last_emi_appe_date_time")
End If
If IsNull(rsAdo("x_last_emi_appe_seq_nbr")) Then
    recrInst.x_last_emi_appe_seq_nbr = 0
Else
    recrInst.x_last_emi_appe_seq_nbr = rsAdo("x_last_emi_appe_seq_nbr")
End If
If IsNull(rsAdo("x_last_rec_appe_date_time")) Then
    recrInst.x_last_rec_appe_date_time = 0
Else
    recrInst.x_last_rec_appe_date_time = rsAdo("x_last_rec_appe_date_time")
End If
If IsNull(rsAdo("x_last_rec_appe_seq_nbr")) Then
    recrInst.x_last_rec_appe_seq_nbr = 0
Else
    recrInst.x_last_rec_appe_seq_nbr = rsAdo("x_last_rec_appe_seq_nbr")
End If
If IsNull(rsAdo("inst_oper_comment")) Then
    recrInst.inst_oper_comment = ""
Else
    recrInst.inst_oper_comment = rsAdo("inst_oper_comment")
End If
If IsNull(rsAdo("inst_va41_audi_seq_nbr")) Then
    recrInst.inst_va41_audi_seq_nbr = 0
Else
    recrInst.inst_va41_audi_seq_nbr = rsAdo("inst_va41_audi_seq_nbr")
End If
'$20070530 JPL If IsNull(rsado("inst_va41_awb_check_text_result")) Then
'$20070530 JPL     recrInst.inst_va41_awb_check_text_result = ""
'$20070530 JPL Else
'$20070530 JPL     recrInst.inst_va41_awb_check_text_result = rsado("inst_va41_awb_check_text_result")
'$20070530 JPL End If
If IsNull(rsAdo("inst_va41_calcul_date_time")) Then
    recrInst.inst_va41_calcul_date_time = 0
Else
    recrInst.inst_va41_calcul_date_time = rsAdo("inst_va41_calcul_date_time")
End If
'$20070530 JPL If IsNull(rsado("inst_va41_contains_unscissored_part")) Then
'$20070530 JPL     recrInst.inst_va41_contains_unscissored_part = 0
'$20070530 JPL Else
'$20070530 JPL     recrInst.inst_va41_contains_unscissored_part = rsado("inst_va41_contains_unscissored_part")
'$20070530 JPL End If
If IsNull(rsAdo("inst_va41_testkey_calculated")) Then
    recrInst.inst_va41_testkey_calculated = 0
Else
    recrInst.inst_va41_testkey_calculated = rsAdo("inst_va41_testkey_calculated")
End If

Exit Function

Error_Handler:
srvrInst_GetBuffer_ODBC = Error

End Function

'---------------------------------------------------------
Public Sub srvrInst_ElpDisplay(recrInst As typerInst)
'---------------------------------------------------------
'frmElpDisplay.fgData.Rows = 79

'frmElpDisplay.fgData.Row = 1
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "Aid"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.Aid

'frmElpDisplay.fgData.Row = 2
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_s_umidl"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_s_umidl

'frmElpDisplay.fgData.Row = 3
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_s_umidh"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_s_umidh

'frmElpDisplay.fgData.Row = 4
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_num"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_num

'frmElpDisplay.fgData.Row = 5
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_type"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_type

'frmElpDisplay.fgData.Row = 6
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_notification_type"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_notification_type

'frmElpDisplay.fgData.Row = 7
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_status"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_status

'frmElpDisplay.fgData.Row = 8
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_related_nbr"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_related_nbr

'frmElpDisplay.fgData.Row = 9
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_appe_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_appe_date_time

'frmElpDisplay.fgData.Row = 10
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_appe_seq_nbr"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_appe_seq_nbr

'frmElpDisplay.fgData.Row = 11
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_unit_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_unit_name

'frmElpDisplay.fgData.Row = 12
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_rp_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_rp_name

'frmElpDisplay.fgData.Row = 13
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_mpfn_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_mpfn_name

'frmElpDisplay.fgData.Row = 14
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_mpfn_handle"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_mpfn_handle

'frmElpDisplay.fgData.Row = 15
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_process_state"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_process_state

'frmElpDisplay.fgData.Row = 16
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_last_mpfn_result"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_last_mpfn_result

'frmElpDisplay.fgData.Row = 17
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_relative_ref"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_relative_ref

'frmElpDisplay.fgData.Row = 18
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_sm2000_priority"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_sm2000_priority

'frmElpDisplay.fgData.Row = 19
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_deferred_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_deferred_time

'frmElpDisplay.fgData.Row = 20
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_crea_appl_serv_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_crea_appl_serv_name

'frmElpDisplay.fgData.Row = 21
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_crea_mpfn_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_crea_mpfn_name

'frmElpDisplay.fgData.Row = 22
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_crea_rp_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_crea_rp_name

'frmElpDisplay.fgData.Row = 23
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_crea_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_crea_date_time

'frmElpDisplay.fgData.Row = 24
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "initial_target_rp_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.initial_target_rp_name

'frmElpDisplay.fgData.Row = 25
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_auth_oper_nickname"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_auth_oper_nickname

'frmElpDisplay.fgData.Row = 26
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_last_oper_nickname"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_last_oper_nickname

'frmElpDisplay.fgData.Row = 27
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_data_last"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_data_last

'frmElpDisplay.fgData.Row = 28
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_token"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_token

'frmElpDisplay.fgData.Row = 29
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_answerback"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_answerback

'frmElpDisplay.fgData.Row = 30
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_appli_rp_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_appli_rp_name

'frmElpDisplay.fgData.Row = 31
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_calc_description"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_calc_description

'frmElpDisplay.fgData.Row = 32
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_calculated_testkey_value"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_calculated_testkey_value
'frmElpDisplay.fgData.Row = 33
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_computation_details"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_computation_details

'frmElpDisplay.fgData.Row = 34
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_corr_X1"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_corr_X1

'frmElpDisplay.fgData.Row = 35
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_corr_X2"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_corr_X2

'frmElpDisplay.fgData.Row = 36
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_crest_com_server_id"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_crest_com_server_id

'frmElpDisplay.fgData.Row = 37
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_crest_gateway_id"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_crest_gateway_id

'frmElpDisplay.fgData.Row = 38
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_extracted_testkey_value"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_extracted_testkey_value

'frmElpDisplay.fgData.Row = 39
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_fax_cui"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_fax_cui

'frmElpDisplay.fgData.Row = 40
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_fax_number"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_fax_number

'frmElpDisplay.fgData.Row = 41
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_fax_origin"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_fax_origin

'frmElpDisplay.fgData.Row = 42
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_fax_tnap_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_fax_tnap_name

'frmElpDisplay.fgData.Row = 43
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_letter_coding"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_letter_coding

'frmElpDisplay.fgData.Row = 44
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_rcv_delivery_status"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_rcv_delivery_status

'frmElpDisplay.fgData.Row = 45
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_X1"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_X1

'frmElpDisplay.fgData.Row = 46
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_X2"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_X2

'frmElpDisplay.fgData.Row = 47
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_X3"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_X3

'frmElpDisplay.fgData.Row = 48
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_X4"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_X4

'frmElpDisplay.fgData.Row = 49
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_branch_info"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_branch_info

'frmElpDisplay.fgData.Row = 50
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_city_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_city_name

'frmElpDisplay.fgData.Row = 51
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_corr_type"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_corr_type

'frmElpDisplay.fgData.Row = 52
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_ctry_code"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_ctry_code

'frmElpDisplay.fgData.Row = 53
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_ctry_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_ctry_name

'frmElpDisplay.fgData.Row = 54
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_institution_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_institution_name

'frmElpDisplay.fgData.Row = 55
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_location"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_location

'frmElpDisplay.fgData.Row = 56
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_network_iapp_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_network_iapp_name

'frmElpDisplay.fgData.Row = 57
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_receiver_secu_iapp_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_receiver_secu_iapp_name

'frmElpDisplay.fgData.Row = 58
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_retry_count"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_retry_count

'frmElpDisplay.fgData.Row = 59
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_retry_cycle"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_retry_cycle

'frmElpDisplay.fgData.Row = 60
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_routing_code"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_routing_code

'frmElpDisplay.fgData.Row = 61
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_telex_number"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_telex_number

'frmElpDisplay.fgData.Row = 62
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_telex_origin"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_telex_origin

'frmElpDisplay.fgData.Row = 63
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_test_comment"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_test_comment

'frmElpDisplay.fgData.Row = 64
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_test_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_test_date_time

'frmElpDisplay.fgData.Row = 65
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_test_system"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_test_system

'frmElpDisplay.fgData.Row = 66
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_testkey_required"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_testkey_required

'frmElpDisplay.fgData.Row = 67
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_testkey_status"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_testkey_status

'frmElpDisplay.fgData.Row = 68
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_tnap_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_tnap_name

'frmElpDisplay.fgData.Row = 69
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_last_emi_appe_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.x_last_emi_appe_date_time

'frmElpDisplay.fgData.Row = 70
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_last_emi_appe_seq_nbr"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.x_last_emi_appe_seq_nbr

'frmElpDisplay.fgData.Row = 71
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_last_rec_appe_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.x_last_rec_appe_date_time

'frmElpDisplay.fgData.Row = 72
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_last_rec_appe_seq_nbr"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.x_last_rec_appe_seq_nbr

'frmElpDisplay.fgData.Row = 73
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_oper_comment"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_oper_comment

'frmElpDisplay.fgData.Row = 74
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_va41_audi_seq_nbr"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_va41_audi_seq_nbr

'frmElpDisplay.fgData.Row = 75
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_va41_awb_check_text_result"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_va41_awb_check_text_result

'frmElpDisplay.fgData.Row = 76
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_va41_calcul_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_va41_calcul_date_time

'frmElpDisplay.fgData.Row = 77
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_va41_contains_unscissored_part"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_va41_contains_unscissored_part

'frmElpDisplay.fgData.Row = 78
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "inst_va41_testkey_calculated"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrInst.inst_va41_testkey_calculated

MsgBox "à faire : frmElpDisplay.Show ", vbCritical '  vbModal

End Sub


'---------------------------------------------------------
Public Sub srvrInst_Init(recrInst As typerInst)
'---------------------------------------------------------

recrInst.Aid = 0
recrInst.inst_s_umidl = 0
recrInst.inst_s_umidh = 0
recrInst.inst_num = 0

recrInst.inst_type = ""
recrInst.inst_notification_type = ""
recrInst.inst_status = ""
recrInst.inst_related_nbr = 0
recrInst.inst_appe_date_time = 0
recrInst.inst_appe_seq_nbr = 0
recrInst.inst_unit_name = ""
recrInst.inst_rp_name = ""
recrInst.inst_mpfn_name = ""
recrInst.inst_mpfn_handle = ""
recrInst.inst_process_state = 0
recrInst.inst_last_mpfn_result = ""
recrInst.inst_relative_ref = 0
recrInst.inst_sm2000_priority = 0
recrInst.inst_deferred_time = 0
recrInst.inst_crea_appl_serv_name = ""
recrInst.inst_crea_mpfn_name = ""
recrInst.inst_crea_rp_name = ""
recrInst.inst_crea_date_time = 0
recrInst.initial_target_rp_name = ""
recrInst.inst_auth_oper_nickname = ""
recrInst.inst_last_oper_nickname = ""
recrInst.inst_data_last = 0
recrInst.inst_token = 0
recrInst.inst_answerback = ""
recrInst.inst_appli_rp_name = ""
recrInst.inst_calc_description = ""
recrInst.inst_calculated_testkey_value = ""
recrInst.inst_computation_details = ""
recrInst.inst_corr_X1 = ""
recrInst.inst_corr_X2 = ""
recrInst.inst_crest_com_server_id = ""
recrInst.inst_crest_gateway_id = ""
recrInst.inst_extracted_testkey_value = ""
recrInst.inst_fax_cui = ""
recrInst.inst_fax_number = ""
recrInst.inst_fax_origin = ""
recrInst.inst_fax_tnap_name = ""
recrInst.inst_letter_coding = ""
recrInst.inst_rcv_delivery_status = ""
recrInst.inst_receiver_X1 = ""
recrInst.inst_receiver_X2 = ""
recrInst.inst_receiver_X3 = ""
recrInst.inst_receiver_X4 = ""
recrInst.inst_receiver_branch_info = ""
recrInst.inst_receiver_city_name = ""
recrInst.inst_receiver_corr_type = ""
recrInst.inst_receiver_ctry_code = ""
recrInst.inst_receiver_ctry_name = ""
recrInst.inst_receiver_institution_name = ""
recrInst.inst_receiver_location = ""
recrInst.inst_receiver_network_iapp_name = ""
recrInst.inst_receiver_secu_iapp_name = ""
recrInst.inst_retry_count = 0
recrInst.inst_retry_cycle = 0
recrInst.inst_routing_code = ""
recrInst.inst_telex_number = ""
recrInst.inst_telex_origin = ""
recrInst.inst_test_comment = ""
recrInst.inst_test_date_time = 0
recrInst.inst_test_system = ""
recrInst.inst_testkey_required = ""
recrInst.inst_testkey_status = ""
recrInst.inst_tnap_name = ""
recrInst.x_last_emi_appe_date_time = 0
recrInst.x_last_emi_appe_seq_nbr = 0
recrInst.x_last_rec_appe_date_time = 0
recrInst.x_last_rec_appe_seq_nbr = 0
recrInst.inst_oper_comment = ""
recrInst.inst_va41_audi_seq_nbr = 0
recrInst.inst_va41_awb_check_text_result = ""
recrInst.inst_va41_calcul_date_time = 0
recrInst.inst_va41_contains_unscissored_part = 0
recrInst.inst_va41_testkey_calculated = 0

End Sub

