Attribute VB_Name = "srvrIntv"
'---------------------------------------------------------
Option Explicit
'---------------------------------------------------------

Public Const constrIntv = "rIntv"

Type typerIntv
    
    Aid                            As Integer                  ' SAA identification
    intv_s_umidl                   As Long                 ' Left part of the internal Swift message reference message)
    intv_s_umidh                   As Long                  ' Right part of the internal Swift message reference
    intv_inst_num                  As Long                 ' Instance index for the message (0=original instance)
    intv_date_time                 As Date                     ' Creation date and time of the intervention
    intv_seq_nbr                   As Double '$2007-01-09 JPLLong                     ' Sequence number to make combination unique on top of date/time in a key
    
    intv_inty_num                  As Long                  ' Intervention type
    intv_inty_name                 As String '* 21              ' Intervention type label
    intv_inty_category             As String '* 32              ' Category in which the interventions are grouped
    intv_oper_nickname             As String '* 11              ' Operator who made the action that implied the creation of the invention - SYSTEM = automated process
    intv_appl_serv_name            As String '* 32              ' application for genarating the intervention
    intv_mpfn_name                 As String '* 32              ' Name of the MPFN function that created the intervention
    intv_appe_date_time            As Date                     ' For types of intervention which have a related appendix
    intv_appe_seq_nbr              As Double '$JPL 2007-01-09 Long                   ' Sequence number to make combination unique on top of date/time in a key
    intv_length                    As Long '$JPL 2012-03-20 Integer                  ' Length of the intervention text
    intv_token                     As Long                 ' CRC on the intervention (generated by SAA)
    intv_text                      As String '* 4000            ' Text of the intervention
    'intv_merged_text               As String
End Type

'---------------------------------------------------------
Public Function srvrIntv_GetBuffer_ODBC(rsAdo As ADODB.Recordset, recrIntv As typerIntv)
'---------------------------------------------------------
On Error GoTo Error_Handler
srvrIntv_GetBuffer_ODBC = Null

recrIntv.Aid = rsAdo("Aid")
recrIntv.intv_s_umidl = rsAdo("intv_s_umidl")
recrIntv.intv_s_umidh = rsAdo("intv_s_umidh")
recrIntv.intv_inst_num = rsAdo("intv_inst_num")
recrIntv.intv_date_time = rsAdo("intv_date_time")
recrIntv.intv_seq_nbr = rsAdo("intv_seq_nbr")

recrIntv.intv_inty_num = rsAdo("intv_inty_num")

recrIntv.intv_inty_name = rsAdo("intv_inty_name")
recrIntv.intv_inty_category = rsAdo("intv_inty_category")
recrIntv.intv_oper_nickname = rsAdo("intv_oper_nickname")
If IsNull(rsAdo("intv_appl_serv_name")) Then
    recrIntv.intv_appl_serv_name = ""
Else
    recrIntv.intv_appl_serv_name = rsAdo("intv_appl_serv_name")

End If
If IsNull(rsAdo("intv_mpfn_name")) Then
    recrIntv.intv_mpfn_name = ""
Else
    recrIntv.intv_mpfn_name = rsAdo("intv_mpfn_name")
End If
recrIntv.intv_appe_date_time = rsAdo("intv_appe_date_time")
recrIntv.intv_appe_seq_nbr = rsAdo("intv_appe_seq_nbr")
recrIntv.intv_length = rsAdo("intv_length")
recrIntv.intv_token = rsAdo("intv_token")
If IsNull(rsAdo("intv_text")) Then
    recrIntv.intv_text = ""
Else
    recrIntv.intv_text = rsAdo("intv_text")
End If

'If IsNull(rsAdo("intv_merged_text")) Then
'    recrIntv.intv_merged_text = ""
'Else
'    recrIntv.intv_merged_text = rsAdo("intv_merged_text")
'End If

Exit Function

Error_Handler:
srvrIntv_GetBuffer_ODBC = Error

End Function

'---------------------------------------------------------
Public Sub srvrIntv_Init(recrIntv As typerIntv)
'---------------------------------------------------------

recrIntv.Aid = 0
recrIntv.intv_s_umidl = 0
recrIntv.intv_s_umidh = 0
recrIntv.intv_inst_num = 0
recrIntv.intv_date_time = 0
recrIntv.intv_seq_nbr = 0

recrIntv.intv_inty_num = 0
recrIntv.intv_inty_name = ""
recrIntv.intv_inty_category = ""
recrIntv.intv_oper_nickname = ""
recrIntv.intv_appl_serv_name = ""
recrIntv.intv_mpfn_name = ""
recrIntv.intv_appe_date_time = 0
recrIntv.intv_appe_seq_nbr = 0
recrIntv.intv_length = 0
recrIntv.intv_token = 0
recrIntv.intv_text = ""
'recrIntv.intv_merged_text = ""
End Sub


'---------------------------------------------------------
Public Sub srvrIntv_ElpDisplay(recrIntv As typerIntv)
'---------------------------------------------------------
'frmElpDisplay.fgData.Rows = 18

'frmElpDisplay.fgData.Row = 1
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "Aid"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.Aid

'frmElpDisplay.fgData.Row = 2
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_s_umidl"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_s_umidl

'frmElpDisplay.fgData.Row = 3
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_s_umidh"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_s_umidh

'frmElpDisplay.fgData.Row = 4
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_inst_num"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_inst_num

'frmElpDisplay.fgData.Row = 5
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_date_time

'frmElpDisplay.fgData.Row = 6
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_seq_nbr"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_seq_nbr

'frmElpDisplay.fgData.Row = 7
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_inty_num"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_inty_num

'frmElpDisplay.fgData.Row = 8
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_inty_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_inty_name

'frmElpDisplay.fgData.Row = 9
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_inty_category"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_inty_category

'frmElpDisplay.fgData.Row = 10
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_oper_nicknamem"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_oper_nickname

'frmElpDisplay.fgData.Row = 11
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_appl_serv_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_appl_serv_name

'frmElpDisplay.fgData.Row = 12
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_mpfn_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_mpfn_name

'frmElpDisplay.fgData.Row = 13
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_appe_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_appe_date_time

'frmElpDisplay.fgData.Row = 14
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_appe_seq_nbr"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_appe_seq_nbr

'frmElpDisplay.fgData.Row = 15
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_length"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_length

'frmElpDisplay.fgData.Row = 16
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_token"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_token

'frmElpDisplay.fgData.Row = 17
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "intv_text"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrIntv.intv_text

MsgBox "à faire : frmElpDisplay.Show ", vbCritical '  vbModal

End Sub








