Attribute VB_Name = "srvrJrnl"
'---------------------------------------------------------
Option Explicit
'---------------------------------------------------------

Public Const constrJrnl = "rJrnl"
Public arrJrnl_Field_Nb As Integer, arrJrnl_Field() As String

Type typerJrnl
    
    Aid                            As Integer                  ' SAA identification
    jrnl_rev_date_time             As Double                    ' Left part of the internal Swift message reference
    jrnl_seq_nbr                   As Long                     ' Right part of the internal Swift message reference
    
    jrnl_comp_name                 As String '* 5               ' Name of the component that generates the event
    jrnl_event_is_security         As Integer                  ' specifies if the event is security related or not
    jrnl_event_num                 As Long                     ' Event number
    jrnl_event_name                As String '* 40              ' Event name
    jrnl_event_class               As String '* 16              ' Event class
    jrnl_event_severity            As String '* 16              ' Event security
    jrnl_event_is_alarm            As Integer                  ' specifies if the event is an alarm
    jrnl_appl_serv_name            As String '* 21              ' application for genarating the event
    jrnl_func_name                 As String '* 21              ' Function for generating the event
    jrnl_hostname                  As String '* 32              ' Hostname the event is generated
    jrnl_oper_nickname             As String '* 11              ' Operator generating the event - Null means generated by SYSTEM
    jrnl_date_time                 As Date                     ' Creation date and time of the event
    jrnl_alarm_status              As String '* 32              ' Alarm status
    jrnl_alarm_dist_status         As String '* 32              ' Alarm distribution status
    jrnl_alarm_date_time           As Date                      ' Date and time of alarm for the event
    jrnl_alarm_oper_nickname       As String '* 32              ' Name of operator who treated the alarm
    jrnl_display_text              As String '* 40              ' 40 first characters of event text
    jrnl_merged_text               As String '* 16              ' Full event text
    jrnl_length                    As Long                      ' Event size
    jrnl_token                     As Long                      ' Event token value
    
    archived                       As Integer                  ' Whether (1) or not (0) the message has been archived in SAA
    restored                       As Integer                  ' Event restored from a backup
    last_update                    As Date                    ' Last update time
    x_umidl                        As Long                     ' Low part of related message key (if the event relates to a message)
    x_umidh                        As Long                     ' Hight part of related message key (if the event relates to a message)

End Type

'---------------------------------------------------------
Public Function srvrJrnl_GetBuffer_ODBC(rsAdo As ADODB.Recordset, recrJrnl As typerJrnl)
'---------------------------------------------------------
On Error GoTo Error_Handler
srvrJrnl_GetBuffer_ODBC = Null

'If IsNull(rsAdo("jrnl_merged_text")) Then
'    recrJrnl.jrnl_merged_text = ""
'Else
    recrJrnl.jrnl_merged_text = rsAdo("jrnl_merged_text")
'End If


recrJrnl.Aid = rsAdo("Aid")
recrJrnl.jrnl_rev_date_time = rsAdo("jrnl_rev_date_time")
recrJrnl.jrnl_seq_nbr = rsAdo("jrnl_seq_nbr")

If IsNull(rsAdo("jrnl_comp_name")) Then
    recrJrnl.jrnl_comp_name = ""
Else
    recrJrnl.jrnl_comp_name = rsAdo("jrnl_comp_name")
End If
If IsNull(rsAdo("jrnl_event_is_security")) Then
    recrJrnl.jrnl_event_is_security = 0
Else
    recrJrnl.jrnl_event_is_security = rsAdo("jrnl_event_is_security")
End If
If IsNull(rsAdo("jrnl_event_num")) Then
    recrJrnl.jrnl_event_num = 0
Else
    recrJrnl.jrnl_event_num = rsAdo("jrnl_event_num")
End If
If IsNull(rsAdo("jrnl_event_name")) Then
    recrJrnl.jrnl_event_name = ""
Else
    recrJrnl.jrnl_event_name = rsAdo("jrnl_event_name")
End If
If IsNull(rsAdo("jrnl_event_class")) Then
    recrJrnl.jrnl_event_class = ""
Else
    recrJrnl.jrnl_event_class = rsAdo("jrnl_event_class")
End If
If IsNull(rsAdo("jrnl_event_severity")) Then
    recrJrnl.jrnl_event_severity = ""
Else
    recrJrnl.jrnl_event_severity = rsAdo("jrnl_event_severity")
End If
If IsNull(rsAdo("jrnl_event_is_alarm")) Then
    recrJrnl.jrnl_event_is_alarm = 0
Else
    recrJrnl.jrnl_event_is_alarm = rsAdo("jrnl_event_is_alarm")
End If
If IsNull(rsAdo("jrnl_appl_serv_name")) Then
    recrJrnl.jrnl_appl_serv_name = ""
Else
    recrJrnl.jrnl_appl_serv_name = rsAdo("jrnl_appl_serv_name")
End If
If IsNull(rsAdo("jrnl_func_name")) Then
    recrJrnl.jrnl_func_name = ""
Else
    recrJrnl.jrnl_func_name = rsAdo("jrnl_func_name")
End If
If IsNull(rsAdo("jrnl_hostname")) Then
    recrJrnl.jrnl_hostname = ""
Else
    recrJrnl.jrnl_hostname = rsAdo("jrnl_hostname")
End If
If IsNull(rsAdo("jrnl_oper_nickname")) Then
    recrJrnl.jrnl_oper_nickname = ""
Else
    recrJrnl.jrnl_oper_nickname = rsAdo("jrnl_oper_nickname")
End If
If IsNull(rsAdo("jrnl_date_time")) Then
    recrJrnl.jrnl_date_time = 0
Else
    recrJrnl.jrnl_date_time = rsAdo("jrnl_date_time")
End If
If IsNull(rsAdo("jrnl_alarm_status")) Then
    recrJrnl.jrnl_alarm_status = ""
Else
    recrJrnl.jrnl_alarm_status = rsAdo("jrnl_alarm_status")
End If
If IsNull(rsAdo("jrnl_alarm_dist_status")) Then
    recrJrnl.jrnl_alarm_dist_status = ""
Else
    recrJrnl.jrnl_alarm_dist_status = rsAdo("jrnl_alarm_dist_status")
End If
If IsNull(rsAdo("jrnl_alarm_date_time")) Then
    recrJrnl.jrnl_alarm_date_time = 0
Else
    recrJrnl.jrnl_alarm_date_time = rsAdo("jrnl_alarm_date_time")
End If
If IsNull(rsAdo("jrnl_alarm_oper_nickname")) Then
    recrJrnl.jrnl_alarm_oper_nickname = ""
Else
    recrJrnl.jrnl_alarm_oper_nickname = rsAdo("jrnl_alarm_oper_nickname")
End If
If IsNull(rsAdo("jrnl_display_text")) Then
    recrJrnl.jrnl_display_text = ""
Else
    recrJrnl.jrnl_display_text = rsAdo("jrnl_display_text")
End If
If IsNull(rsAdo("jrnl_length")) Then
    recrJrnl.jrnl_length = 0
Else
    recrJrnl.jrnl_length = rsAdo("jrnl_length")
End If
If IsNull(rsAdo("jrnl_token")) Then
    recrJrnl.jrnl_token = 0
Else
    recrJrnl.jrnl_token = rsAdo("jrnl_token")
End If
If IsNull(rsAdo("archived")) Then
    recrJrnl.archived = 0
Else
    recrJrnl.archived = rsAdo("archived")
End If
If IsNull(rsAdo("restored")) Then
    recrJrnl.restored = 0
Else
    recrJrnl.restored = rsAdo("restored")
End If
If IsNull(rsAdo("last_update")) Then
    recrJrnl.last_update = 0
Else
    recrJrnl.last_update = rsAdo("last_update")
End If
If IsNull(rsAdo("x_umidl")) Then
    recrJrnl.x_umidl = 0
Else
    recrJrnl.x_umidl = rsAdo("x_umidl")
End If
If IsNull(rsAdo("x_umidh")) Then
    recrJrnl.x_umidh = 0
Else
    recrJrnl.x_umidh = rsAdo("x_umidh")
End If

Exit Function

Error_Handler:
srvrJrnl_GetBuffer_ODBC = Error

End Function

'---------------------------------------------------------
Public Sub srvrJrnl_Init(recrJrnl As typerJrnl)
'---------------------------------------------------------

recrJrnl.Aid = 0
recrJrnl.jrnl_rev_date_time = 0
recrJrnl.jrnl_seq_nbr = 0

recrJrnl.jrnl_comp_name = ""
recrJrnl.jrnl_event_is_security = 0
recrJrnl.jrnl_event_num = 0
recrJrnl.jrnl_event_name = ""
recrJrnl.jrnl_event_class = ""
recrJrnl.jrnl_event_severity = ""
recrJrnl.jrnl_event_is_alarm = 0
recrJrnl.jrnl_appl_serv_name = ""
recrJrnl.jrnl_func_name = ""
recrJrnl.jrnl_hostname = ""
recrJrnl.jrnl_oper_nickname = ""
recrJrnl.jrnl_date_time = 0
recrJrnl.jrnl_alarm_status = ""
recrJrnl.jrnl_alarm_dist_status = ""
recrJrnl.jrnl_alarm_date_time = 0
recrJrnl.jrnl_alarm_oper_nickname = ""
recrJrnl.jrnl_display_text = ""
recrJrnl.jrnl_merged_text = ""
recrJrnl.jrnl_length = 0
recrJrnl.jrnl_token = 0

recrJrnl.archived = 0
recrJrnl.restored = 0
recrJrnl.last_update = 0
recrJrnl.x_umidl = 0
recrJrnl.x_umidh = 0

End Sub

'---------------------------------------------------------
Public Sub srvrJrnl_ElpDisplay(recrJrnl As typerJrnl)
'---------------------------------------------------------
'frmElpDisplay.fgData.Rows = 29

'frmElpDisplay.fgData.Row = 1
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "Aid"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.Aid

'frmElpDisplay.fgData.Row = 2
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_rev_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_rev_date_time

'frmElpDisplay.fgData.Row = 3
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_seq_nbr"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_seq_nbr

'frmElpDisplay.fgData.Row = 4
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_comp_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_comp_name

'frmElpDisplay.fgData.Row = 5
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_event_is_security"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_event_is_security

'frmElpDisplay.fgData.Row = 6
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_event_num"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_event_num

'frmElpDisplay.fgData.Row = 7
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_event_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_event_name

'frmElpDisplay.fgData.Row = 8
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_event_class"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_event_class

'frmElpDisplay.fgData.Row = 9
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_event_severity"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_event_severity

'frmElpDisplay.fgData.Row = 10
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_event_is_alarm"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_event_is_alarm

'frmElpDisplay.fgData.Row = 11
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_appl_serv_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_appl_serv_name

'frmElpDisplay.fgData.Row = 12
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_func_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_func_name

'frmElpDisplay.fgData.Row = 13
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_hostname"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_hostname

'frmElpDisplay.fgData.Row = 14
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_oper_nickname"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_oper_nickname

'frmElpDisplay.fgData.Row = 15
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_date_time

'frmElpDisplay.fgData.Row = 16
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_alarm_status"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_alarm_status

'frmElpDisplay.fgData.Row = 17
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_alarm_dist_status"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_alarm_dist_status

'frmElpDisplay.fgData.Row = 18
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_alarm_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_alarm_date_time

'frmElpDisplay.fgData.Row = 19
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_alarm_oper_nickname"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_alarm_oper_nickname

'frmElpDisplay.fgData.Row = 20
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_display_text"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_display_text

'frmElpDisplay.fgData.Row = 21
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_merged_text"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_merged_text

'frmElpDisplay.fgData.Row = 22
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_length"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_length

'frmElpDisplay.fgData.Row = 23
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "jrnl_token"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.jrnl_token

'frmElpDisplay.fgData.Row = 24
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "archived"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.archived

'frmElpDisplay.fgData.Row = 25
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "restored"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.restored

'frmElpDisplay.fgData.Row = 26
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "last_update"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.last_update

'frmElpDisplay.fgData.Row = 27
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_umidl"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.x_umidl

'frmElpDisplay.fgData.Row = 28
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_umidh"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrJrnl.x_umidh

MsgBox "à faire : frmElpDisplay.Show ", vbCritical '  vbModal

End Sub




