Attribute VB_Name = "srvrMesg"
'---------------------------------------------------------
Option Explicit
'---------------------------------------------------------

Public Const constrMesg = "rMesg"

Type typerMesg
    
    Aid                            As Integer                  ' SAA identification
    mesg_s_umidl                   As Long                     ' Left part of the internal Swift message reference
    mesg_s_umidh                   As Long                     ' Right part of the internal Swift message reference
    
    mesg_validation_requested      As String '* 18              ' Level of validation on a added message
    mesg_validation_passed         As String '* 18              ' Level of validation that was passed by the message
    mesg_class                     As String '* 16              ' Message class
    mesg_related_s_umid            As String '* 16              ' Internal Swift message reference related to this present message
    mesg_is_text_readonly          As Integer                  ' Text message read only (1) or not (0)
    mesg_is_delete_inhibited       As Integer                  ' Text message delete able (1) or not (0)
    mesg_is_text_modified          As Integer                  ' Text message has been modified (1) or not (0)
    mesg_is_partial                As Integer                  ' Text message incomplete (1) or not (0)
    mesg_status                    As String '* 12              ' Live or Complete
    mesg_crea_appl_serv_name       As String '* 24              ' Name of the application interface that created the message
    mesg_crea_mpfn_name            As String '* 24              ' Name of the SAA function that created the message
    mesg_crea_rp_name              As String '* 24              ' Name of the SAA queue where the created message was put - It is linked to the previous field
    mesg_crea_oper_nickname        As String '* 11              ' Short name of the operator that created the message - SYSTEM if automated process
    mesg_crea_date_time            As Date                     ' Complete date and time of message creation in SAA
    mesg_mod_oper_nickname         As String '* 11              ' Short name of the operator that modified the message
    mesg_mod_date_time             As Date                     ' Complete date and time of creation or last modification in SAA
    mesg_verf_oper_nickname        As String '* 11              ' Short name of the operator that verified the message
    mesg_data_last                 As Long                     ' Length of the encapsulated field
    mesg_token                     As Long                     ' CRC on the message (generated by SAA)
    mesg_batch_reference           As String '* 46              ' MXS batch reference
    mesg_cas_sender_reference      As String '* 40              ' Sender's reference for messages received by the CAS protocol
    mesg_cas_target_rp_name        As String '* 20              ' Queue name in which a message received by the CAS protocol was requested to be placed
    mesg_ccy_amount                As String '* 80              ' ccy - amount strings separated by "/". Used by TELEX interface to ganerate the TestKey
    mesg_copy_service_id           As String '* 4               ' Involved FIN - Copy service identifier related to the message
    mesg_data_keyword1             As String '* 80
    mesg_data_keyword2             As String '* 80
    mesg_data_keyword3             As String '* 80
    mesg_delv_overdue_warn_req     As Integer                  ' Indicates whether (1) or not (0) the network should generate overdue warning in case of delays
    mesg_fin_ccy_amount            As String '* 24              ' ccy (3C) - amount (16N,6N) that appear in the message header
    mesg_fin_value_date            As String '* 6               ' Value date that appears in the message header (YYMMDD)
    mesg_frmt_name                 As String '* 17              ' Format of the message text : Swift - Telex - Internal
    mesg_is_live                   As Integer                  ' Indicates whether the message is a live (1) or test (0) message
    mesg_is_retrieved              As Integer                  ' Message is network retrieved
    mesg_mesg_user_group           As String '* 24              ' Not used
    mesg_nature                    As String '* 14              ' High level grouping of different message types : dépends on the message format, Swift or Telex
    mesg_network_appl_ind          As String '* 3               ' Network application responsible for handling the message
    mesg_network_delv_notif_req    As Integer                  ' Indicates whether (1) or not (0) the network should generate a delivery notification for the message
    mesg_network_obso_period       As Long                     ' Network obsolescence period (Delta Time)
    mesg_network_priority          As String '* 12
    mesg_possible_dup_creation     As String '* 8               ' Contains values if the message has been flagged as duplicate when it has been created
    mesg_receiver_alia_name        As String '* 32              ' Alias name of the receiver
    mesg_receiver_swift_address    As String '* 12              ' BIC identifying the message receiver
    mesg_recovery_accept_info      As String '* 80              ' Alias name of the receiver
    mesg_rel_trn_ref               As String '* 80              ' If this message refers to another message, this field contains the transaction reference of that message
    mesg_release_info              As String ''* 32              ' Payment Release Information (COPY)
    mesg_security_iapp_name        As String '* 80
    mesg_security_required         As Integer                  ' Security required (1) or not (0) - Overwrite CIF if defined
    mesg_sender_X1                 As String '* 11              ' BIC 11 of the message sender
    mesg_sender_X2                 As String '* 21              ' Sender department name
    mesg_sender_X3                 As String '* 21              ' Sender last name
    mesg_sender_X4                 As String '* 21              ' Sender first name
    mesg_sender_branch_info        As String '* 71              ' Sender branch name
    mesg_sender_city_name          As String '* 36              ' Sender city name
    mesg_sender_corr_type          As String '* 24              ' Type of sender correspondent
    mesg_sender_ctry_code          As String '* 3               ' Sender country code
    mesg_sender_ctry_name          As String '* 71              ' Sender country name
    mesg_sender_institution_name   As String '* 106             ' Sender institution name
    mesg_sender_location           As String '* 106             ' Sender location name
    mesg_sender_swift_address      As String '* 12              ' BIC 12 identifying the message sender
    mesg_sub_format                As String '* 6               ' INPUT = sent to Swift / OUTPUT = received from Swift
    mesg_syntax_table_ver          As String '* 8               ' Syntax version used to create the message - YYMM = Usual format
    mesg_template_name             As String '* 32              ' If the message has been created by using a message template
    mesg_trn_ref                   As String '* 16              ' Transaction reference for the message - Field 20 or 21 in the message text block
    mesg_type                      As String '* 3
    mesg_user_issued_as_pde        As Integer                  ' Whether (1) or not (0) the sender of the message has issued the message as a possible duplicate
    mesg_user_priority_code        As String '* 4
    mesg_user_reference_text       As String '* 30              ' Sender to Receiver reference for this message
    mesg_uumid                     As String '* 50              ' User part of a unique message identifier - UMID
    mesg_uumid_suffix              As Long                     ' Suffix to the mesg_uumid to make it unique
    mesg_zz41_is_possible_dup      As Integer
    x_fin_ccy                      As String '* 3               ' Currency part of the mesg_fin_ccy_amount field
    x_fin_amount                   As Currency                 ' Amount part of the mesg_fin_ccy_amount field
    x_fin_value_date               As Date                     ' Mesg_fin_value_date converted to a DateTime field
    x_fin_ocmt_ccy                 As String '* 3               ' Obsolete
    x_fin_ocmt_amount              As Currency                 ' Obsolete
    x_own_lt                       As String '* 8               ' BIC of sender (input message) or receiver (output message)
    x_inst0_unit_name              As String '* 32              ' Name of the unit to which belongs the original instance of this message
    x_category                     As String '* 1
    x_receiver_X1                  As String '* 11              ' BIC 11 of the original instance receiver
    x_receiver_X2                  As String '* 21              ' Original instance receiver department name
    x_receiver_X3                  As String '* 21              ' Original instance receiver last name
    x_receiver_X4                  As String '* 21              ' Original instance receiver first name
    archived                       As Integer                  ' Whether (1) or not (0) the message has been archived in SAA
    last_update                    As Date                     ' Date and time of the last update of the message in the SIDE Database
    restored                       As Integer                  ' Whether (1) or not (0) the message has been restored from an archive (swift or side)
    set_id                         As Long                     ' Id of the archive if the message has been restored

    mesg_identifier                 As String
End Type

'---------------------------------------------------------
Public Function srvrMesg_GetBuffer_ODBC(rsADO As ADODB.Recordset, recrMesg As typerMesg)
'---------------------------------------------------------
On Error GoTo Error_Handler
srvrMesg_GetBuffer_ODBC = Null

recrMesg.Aid = rsADO("Aid")
recrMesg.mesg_s_umidl = rsADO("mesg_s_umidl")
recrMesg.mesg_s_umidh = rsADO("mesg_s_umidh")
recrMesg.mesg_s_umidh = rsADO("mesg_s_umidh")
If recrMesg.mesg_s_umidl = 1042567924 And recrMesg.mesg_s_umidh = -11269 Then
    Debug.Print recrMesg.mesg_s_umidh
End If

recrMesg.mesg_validation_requested = rsADO("mesg_validation_requested")
recrMesg.mesg_validation_passed = rsADO("mesg_validation_passed")
recrMesg.mesg_class = rsADO("mesg_class")
If IsNull(rsADO("mesg_related_s_umid")) Then
    recrMesg.mesg_related_s_umid = ""
Else
    recrMesg.mesg_related_s_umid = rsADO("mesg_related_s_umid")
End If
recrMesg.mesg_is_text_readonly = rsADO("mesg_is_text_readonly")
recrMesg.mesg_is_delete_inhibited = rsADO("mesg_is_delete_inhibited")
recrMesg.mesg_is_text_modified = rsADO("mesg_is_text_modified")
recrMesg.mesg_is_partial = rsADO("mesg_is_partial")
If IsNull(rsADO("mesg_status")) Then
    recrMesg.mesg_status = ""
Else
    recrMesg.mesg_status = rsADO("mesg_status")
End If
recrMesg.mesg_crea_appl_serv_name = rsADO("mesg_crea_appl_serv_name")
recrMesg.mesg_crea_mpfn_name = rsADO("mesg_crea_mpfn_name")
recrMesg.mesg_crea_rp_name = rsADO("mesg_crea_rp_name")
recrMesg.mesg_crea_oper_nickname = rsADO("mesg_crea_oper_nickname")
recrMesg.mesg_crea_date_time = rsADO("mesg_crea_date_time")
recrMesg.mesg_mod_oper_nickname = rsADO("mesg_mod_oper_nickname")
recrMesg.mesg_mod_date_time = rsADO("mesg_mod_date_time")
If IsNull(rsADO("mesg_verf_oper_nickname")) Then
    recrMesg.mesg_verf_oper_nickname = ""
Else
    recrMesg.mesg_verf_oper_nickname = rsADO("mesg_verf_oper_nickname")
End If
If IsNull(rsADO("mesg_data_last")) Then
    recrMesg.mesg_data_last = 0
Else
    recrMesg.mesg_data_last = rsADO("mesg_data_last")
End If
If IsNull(rsADO("mesg_token")) Then
    recrMesg.mesg_token = 0
Else
    recrMesg.mesg_token = rsADO("mesg_token")
End If
If IsNull(rsADO("mesg_batch_reference")) Then
    recrMesg.mesg_batch_reference = ""
Else
    recrMesg.mesg_batch_reference = rsADO("mesg_batch_reference")
End If
If IsNull(rsADO("mesg_cas_sender_reference")) Then
    recrMesg.mesg_cas_sender_reference = ""
Else
    recrMesg.mesg_cas_sender_reference = rsADO("mesg_cas_sender_reference")
End If
If IsNull(rsADO("mesg_cas_target_rp_name")) Then
    recrMesg.mesg_cas_target_rp_name = ""
Else
    recrMesg.mesg_cas_target_rp_name = rsADO("mesg_cas_target_rp_name")
End If
If IsNull(rsADO("mesg_ccy_amount")) Then
    recrMesg.mesg_ccy_amount = ""
Else
    recrMesg.mesg_ccy_amount = rsADO("mesg_ccy_amount")
End If
If IsNull(rsADO("mesg_copy_service_id")) Then
    recrMesg.mesg_copy_service_id = ""
Else
    recrMesg.mesg_copy_service_id = rsADO("mesg_copy_service_id")
End If
If IsNull(rsADO("mesg_data_keyword1")) Then
    recrMesg.mesg_data_keyword1 = ""
Else
    recrMesg.mesg_data_keyword1 = rsADO("mesg_data_keyword1")
End If
If IsNull(rsADO("mesg_data_keyword2")) Then
    recrMesg.mesg_data_keyword2 = ""
Else
    recrMesg.mesg_data_keyword2 = rsADO("mesg_data_keyword2")
End If
If IsNull(rsADO("mesg_data_keyword3")) Then
    recrMesg.mesg_data_keyword3 = ""
Else
    recrMesg.mesg_data_keyword3 = rsADO("mesg_data_keyword3")
End If
recrMesg.mesg_delv_overdue_warn_req = rsADO("mesg_delv_overdue_warn_req")
If IsNull(rsADO("mesg_fin_ccy_amount")) Then
    recrMesg.mesg_fin_ccy_amount = ""
Else
    recrMesg.mesg_fin_ccy_amount = rsADO("mesg_fin_ccy_amount")
End If
If IsNull(rsADO("mesg_fin_value_date")) Then
    recrMesg.mesg_fin_value_date = ""
Else
    recrMesg.mesg_fin_value_date = rsADO("mesg_fin_value_date")
End If
recrMesg.mesg_frmt_name = rsADO("mesg_frmt_name")
If IsNull(rsADO("mesg_is_live")) Then
    recrMesg.mesg_is_live = 0
Else
    recrMesg.mesg_is_live = rsADO("mesg_is_live")
End If

If IsNull(rsADO("mesg_is_retrieved")) Then
    recrMesg.mesg_is_retrieved = 0
Else
    recrMesg.mesg_is_retrieved = rsADO("mesg_is_retrieved")
End If
If IsNull(rsADO("mesg_mesg_user_group")) Then
    recrMesg.mesg_mesg_user_group = ""
Else
    recrMesg.mesg_mesg_user_group = rsADO("mesg_mesg_user_group")
End If
recrMesg.mesg_nature = rsADO("mesg_nature")
If IsNull(rsADO("mesg_network_appl_ind")) Then
    recrMesg.mesg_network_appl_ind = ""
Else
    recrMesg.mesg_network_appl_ind = rsADO("mesg_network_appl_ind")
End If
'recrMesg.mesg_network_delv_notif_req = rsADO("mesg_network_delv_notif_req")

'ajout Kokou 22/03/2023

If IsNull(rsADO("mesg_network_delv_notif_req")) Then
recrMesg.mesg_network_delv_notif_req = 0
Else
recrMesg.mesg_network_delv_notif_req = rsADO("mesg_network_delv_notif_req")
End If

'FIN AJOUT


If IsNull(rsADO("mesg_network_obso_period")) Then
    recrMesg.mesg_network_obso_period = 0
Else
    recrMesg.mesg_network_obso_period = rsADO("mesg_network_obso_period")
End If
If IsNull(rsADO("mesg_network_priority")) Then
    recrMesg.mesg_network_priority = ""
Else
    recrMesg.mesg_network_priority = rsADO("mesg_network_priority")
End If
If IsNull(rsADO("mesg_possible_dup_creation")) Then
    recrMesg.mesg_possible_dup_creation = ""
Else
    recrMesg.mesg_possible_dup_creation = rsADO("mesg_possible_dup_creation")
End If
If IsNull(rsADO("mesg_receiver_alia_name")) Then
    recrMesg.mesg_receiver_alia_name = ""
Else
    recrMesg.mesg_receiver_alia_name = rsADO("mesg_receiver_alia_name")
End If
If IsNull(rsADO("mesg_receiver_swift_address")) Then
    recrMesg.mesg_receiver_swift_address = ""
Else
    recrMesg.mesg_receiver_swift_address = rsADO("mesg_receiver_swift_address")
End If
If IsNull(rsADO("mesg_recovery_accept_info")) Then
    recrMesg.mesg_recovery_accept_info = ""
Else
    recrMesg.mesg_recovery_accept_info = rsADO("mesg_recovery_accept_info")
End If
If IsNull(rsADO("mesg_rel_trn_ref")) Then
    recrMesg.mesg_rel_trn_ref = ""
Else
    recrMesg.mesg_rel_trn_ref = rsADO("mesg_rel_trn_ref")
End If
If IsNull(rsADO("mesg_release_info")) Then
    recrMesg.mesg_release_info = ""
Else
    recrMesg.mesg_release_info = rsADO("mesg_release_info")
End If
If IsNull(rsADO("mesg_security_iapp_name")) Then
    recrMesg.mesg_security_iapp_name = ""
Else
    recrMesg.mesg_security_iapp_name = rsADO("mesg_security_iapp_name")
End If
If IsNull(rsADO("mesg_security_required")) Then
    recrMesg.mesg_security_required = 0
Else
    recrMesg.mesg_security_required = rsADO("mesg_security_required")
End If
recrMesg.mesg_sender_X1 = rsADO("mesg_sender_X1")
If IsNull(rsADO("mesg_sender_X2")) Then
    recrMesg.mesg_sender_X2 = ""
Else
    recrMesg.mesg_sender_X2 = rsADO("mesg_sender_X2")
End If
If IsNull(rsADO("mesg_sender_X3")) Then
    recrMesg.mesg_sender_X3 = ""
Else
    recrMesg.mesg_sender_X3 = rsADO("mesg_sender_X3")
End If
If IsNull(rsADO("mesg_sender_X4")) Then
    recrMesg.mesg_sender_X4 = ""
Else
    recrMesg.mesg_sender_X4 = rsADO("mesg_sender_X4")
End If
If IsNull(rsADO("mesg_sender_branch_info")) Then
    recrMesg.mesg_sender_branch_info = ""
Else
    recrMesg.mesg_sender_branch_info = rsADO("mesg_sender_branch_info")
End If
If IsNull(rsADO("mesg_sender_city_name")) Then
    recrMesg.mesg_sender_city_name = ""
Else
    recrMesg.mesg_sender_city_name = rsADO("mesg_sender_city_name")
End If
recrMesg.mesg_sender_corr_type = rsADO("mesg_sender_corr_type")
If IsNull(rsADO("mesg_sender_ctry_code")) Then
    recrMesg.mesg_sender_ctry_code = ""
Else
    recrMesg.mesg_sender_ctry_code = rsADO("mesg_sender_ctry_code")
End If
If IsNull(rsADO("mesg_sender_ctry_name")) Then
    recrMesg.mesg_sender_ctry_name = ""
Else
    recrMesg.mesg_sender_ctry_name = rsADO("mesg_sender_ctry_name")
End If
If IsNull(rsADO("mesg_sender_institution_name")) Then
    recrMesg.mesg_sender_institution_name = ""
Else
    recrMesg.mesg_sender_institution_name = rsADO("mesg_sender_institution_name")
End If
If IsNull(rsADO("mesg_sender_location")) Then
    recrMesg.mesg_sender_location = ""
Else
    recrMesg.mesg_sender_location = rsADO("mesg_sender_location")
End If
If IsNull(rsADO("mesg_sender_swift_address")) Then
    recrMesg.mesg_sender_swift_address = ""
Else
    recrMesg.mesg_sender_swift_address = rsADO("mesg_sender_swift_address")
End If
If IsNull(rsADO("mesg_sub_format")) Then
    recrMesg.mesg_sub_format = ""
Else
    recrMesg.mesg_sub_format = rsADO("mesg_sub_format")
End If
If IsNull(rsADO("mesg_syntax_table_ver")) Then
    recrMesg.mesg_syntax_table_ver = ""
Else
    recrMesg.mesg_syntax_table_ver = rsADO("mesg_syntax_table_ver")
End If
If IsNull(rsADO("mesg_template_name")) Then
    recrMesg.mesg_template_name = ""
Else
    recrMesg.mesg_template_name = rsADO("mesg_template_name")
End If
If IsNull(rsADO("mesg_trn_ref")) Then
    recrMesg.mesg_trn_ref = ""
Else
    recrMesg.mesg_trn_ref = rsADO("mesg_trn_ref")
End If
If IsNull(rsADO("mesg_type")) Then
    recrMesg.mesg_type = ""
Else
    recrMesg.mesg_type = rsADO("mesg_type")
End If
If IsNull(rsADO("mesg_user_issued_as_pde")) Then
    recrMesg.mesg_user_issued_as_pde = 0
Else
    recrMesg.mesg_user_issued_as_pde = rsADO("mesg_user_issued_as_pde")
End If
If IsNull(rsADO("mesg_user_priority_code")) Then
    recrMesg.mesg_user_priority_code = ""
Else
    recrMesg.mesg_user_priority_code = rsADO("mesg_user_priority_code")
End If
If IsNull(rsADO("mesg_user_reference_text")) Then
    recrMesg.mesg_user_reference_text = ""
Else
    recrMesg.mesg_user_reference_text = rsADO("mesg_user_reference_text")
End If
recrMesg.mesg_uumid = rsADO("mesg_uumid")
recrMesg.mesg_uumid_suffix = rsADO("mesg_uumid_suffix")
If IsNull(rsADO("mesg_zz41_is_possible_dup")) Then
    recrMesg.mesg_zz41_is_possible_dup = 0
Else
    recrMesg.mesg_zz41_is_possible_dup = rsADO("mesg_zz41_is_possible_dup")
End If
If IsNull(rsADO("x_fin_ccy")) Then
    recrMesg.x_fin_ccy = ""
Else
    recrMesg.x_fin_ccy = rsADO("x_fin_ccy")
End If
If IsNull(rsADO("x_fin_amount")) Then
    recrMesg.x_fin_amount = 0
Else
    recrMesg.x_fin_amount = rsADO("x_fin_amount")
End If
If IsNull(rsADO("x_fin_value_date")) Then
    recrMesg.x_fin_value_date = 0
Else
    recrMesg.x_fin_value_date = rsADO("x_fin_value_date")
End If
If IsNull(rsADO("x_fin_ocmt_ccy")) Then
    recrMesg.x_fin_ocmt_ccy = ""
Else
    recrMesg.x_fin_ocmt_ccy = rsADO("x_fin_ocmt_ccy")
End If
If IsNull(rsADO("x_fin_ocmt_amount")) Then
    recrMesg.x_fin_ocmt_amount = 0
Else
    recrMesg.x_fin_ocmt_amount = rsADO("x_fin_ocmt_amount")
End If
If IsNull(rsADO("x_own_lt")) Then
    recrMesg.x_own_lt = ""
Else
    recrMesg.x_own_lt = rsADO("x_own_lt")
End If
If IsNull(rsADO("x_inst0_unit_name")) Then
    recrMesg.x_inst0_unit_name = ""
Else
    recrMesg.x_inst0_unit_name = rsADO("x_inst0_unit_name")
End If
If IsNull(rsADO("x_category")) Then
    recrMesg.x_category = ""
Else
    recrMesg.x_category = rsADO("x_category")
End If
If IsNull(rsADO("x_receiver_X1")) Then
    recrMesg.x_receiver_X1 = ""
Else
    recrMesg.x_receiver_X1 = rsADO("x_receiver_X1")
End If
If IsNull(rsADO("x_receiver_X2")) Then
    recrMesg.x_receiver_X2 = ""
Else
    recrMesg.x_receiver_X2 = rsADO("x_receiver_X2")
End If
If IsNull(rsADO("x_receiver_X3")) Then
    recrMesg.x_receiver_X3 = ""
Else
    recrMesg.x_receiver_X3 = rsADO("x_receiver_X3")
End If
If IsNull(rsADO("x_receiver_X4")) Then
    recrMesg.x_receiver_X4 = ""
Else
    recrMesg.x_receiver_X4 = rsADO("x_receiver_X4")
End If
recrMesg.archived = rsADO("archived")
If IsNull(rsADO("last_update")) Then
    recrMesg.last_update = 0
Else
    recrMesg.last_update = rsADO("last_update")
End If
recrMesg.restored = rsADO("restored")
If IsNull(rsADO("set_id")) Then
    recrMesg.set_id = 0
Else
    recrMesg.set_id = rsADO("set_id")
End If

If IsNull(rsADO("mesg_identifier")) Then
    recrMesg.mesg_identifier = ""
Else
    recrMesg.mesg_identifier = rsADO("mesg_identifier")
End If

'End If

Exit Function

Error_Handler:
srvrMesg_GetBuffer_ODBC = Error

End Function

'---------------------------------------------------------
Public Sub srvrMesg_Init(recrMesg As typerMesg)
'---------------------------------------------------------

recrMesg.Aid = 0
recrMesg.mesg_s_umidl = 0
recrMesg.mesg_s_umidh = 0

recrMesg.mesg_validation_requested = ""
recrMesg.mesg_validation_passed = ""
recrMesg.mesg_class = ""
recrMesg.mesg_related_s_umid = ""
recrMesg.mesg_is_text_readonly = 0
recrMesg.mesg_is_delete_inhibited = 0
recrMesg.mesg_is_text_modified = 0
recrMesg.mesg_is_partial = 0
recrMesg.mesg_status = ""
recrMesg.mesg_crea_appl_serv_name = ""
recrMesg.mesg_crea_mpfn_name = ""
recrMesg.mesg_crea_rp_name = ""
recrMesg.mesg_crea_oper_nickname = ""
recrMesg.mesg_crea_date_time = 0
recrMesg.mesg_mod_oper_nickname = ""
recrMesg.mesg_mod_date_time = 0
recrMesg.mesg_verf_oper_nickname = ""
recrMesg.mesg_data_last = 0
recrMesg.mesg_token = 0
recrMesg.mesg_batch_reference = ""
recrMesg.mesg_cas_sender_reference = ""
recrMesg.mesg_cas_target_rp_name = ""
recrMesg.mesg_ccy_amount = ""
recrMesg.mesg_copy_service_id = ""
recrMesg.mesg_data_keyword1 = ""
recrMesg.mesg_data_keyword2 = ""
recrMesg.mesg_data_keyword3 = ""
recrMesg.mesg_delv_overdue_warn_req = 0
recrMesg.mesg_fin_ccy_amount = ""
recrMesg.mesg_fin_value_date = ""
recrMesg.mesg_frmt_name = ""
recrMesg.mesg_is_live = 0
recrMesg.mesg_is_retrieved = 0
recrMesg.mesg_mesg_user_group = ""
recrMesg.mesg_nature = ""
recrMesg.mesg_network_appl_ind = ""
recrMesg.mesg_network_delv_notif_req = 0
recrMesg.mesg_network_obso_period = 0
recrMesg.mesg_network_priority = ""
recrMesg.mesg_possible_dup_creation = ""
recrMesg.mesg_receiver_alia_name = ""
recrMesg.mesg_receiver_swift_address = ""
recrMesg.mesg_recovery_accept_info = ""
recrMesg.mesg_rel_trn_ref = ""
recrMesg.mesg_release_info = ""
recrMesg.mesg_security_iapp_name = ""
recrMesg.mesg_security_required = 0
recrMesg.mesg_sender_X1 = ""
recrMesg.mesg_sender_X2 = ""
recrMesg.mesg_sender_X3 = ""
recrMesg.mesg_sender_X4 = ""
recrMesg.mesg_sender_branch_info = ""
recrMesg.mesg_sender_city_name = ""
recrMesg.mesg_sender_corr_type = ""
recrMesg.mesg_sender_ctry_code = ""
recrMesg.mesg_sender_ctry_name = ""
recrMesg.mesg_sender_institution_name = ""
recrMesg.mesg_sender_location = ""
recrMesg.mesg_sender_swift_address = ""
recrMesg.mesg_sub_format = ""
recrMesg.mesg_syntax_table_ver = ""
recrMesg.mesg_template_name = ""
recrMesg.mesg_trn_ref = ""
recrMesg.mesg_type = ""
recrMesg.mesg_user_issued_as_pde = 0
recrMesg.mesg_user_priority_code = ""
recrMesg.mesg_user_reference_text = ""
recrMesg.mesg_uumid = ""
recrMesg.mesg_uumid_suffix = 0
recrMesg.mesg_zz41_is_possible_dup = 0

recrMesg.x_fin_ccy = ""
recrMesg.x_fin_amount = 0
recrMesg.x_fin_value_date = 0
recrMesg.x_fin_ocmt_ccy = ""
recrMesg.x_fin_ocmt_amount = 0
recrMesg.x_own_lt = ""
recrMesg.x_inst0_unit_name = ""
recrMesg.x_category = ""
recrMesg.x_receiver_X1 = ""
recrMesg.x_receiver_X2 = ""
recrMesg.x_receiver_X3 = ""
recrMesg.x_receiver_X4 = ""
recrMesg.archived = 0
recrMesg.last_update = 0
recrMesg.restored = 0
recrMesg.set_id = 0

End Sub

'---------------------------------------------------------
Public Sub srvrMesg_ElpDisplay(recrMesg As typerMesg)
'---------------------------------------------------------
'frmElpDisplay.fgData.Rows = 90

'frmElpDisplay.fgData.Row = 1
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "Aid"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.Aid

'frmElpDisplay.fgData.Row = 2
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_s_umidl"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_s_umidl

'frmElpDisplay.fgData.Row = 3
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_s_umidh"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_s_umidh

'frmElpDisplay.fgData.Row = 4
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_validation_requested"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_validation_requested

'frmElpDisplay.fgData.Row = 5
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_validation_passed"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_validation_passed

'frmElpDisplay.fgData.Row = 6
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_class"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_class

'frmElpDisplay.fgData.Row = 7
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_related_s_umid"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_related_s_umid

'frmElpDisplay.fgData.Row = 8
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_is_text_readonly"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_is_text_readonly

'frmElpDisplay.fgData.Row = 9
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_is_delete_inhibited"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_is_delete_inhibited

'frmElpDisplay.fgData.Row = 10
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_is_text_modified"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_is_text_modified

'frmElpDisplay.fgData.Row = 11
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_is_partial"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_is_partial

'frmElpDisplay.fgData.Row = 12
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_status"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_status

'frmElpDisplay.fgData.Row = 13
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_crea_appl_serv_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_crea_appl_serv_name

'frmElpDisplay.fgData.Row = 14
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_crea_mpfn_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_crea_mpfn_name

'frmElpDisplay.fgData.Row = 15
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_crea_rp_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_crea_rp_name

'frmElpDisplay.fgData.Row = 16
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_crea_oper_nickname"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_crea_oper_nickname

'frmElpDisplay.fgData.Row = 17
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_crea_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_crea_date_time

'frmElpDisplay.fgData.Row = 18
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_mod_oper_nickname"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_mod_oper_nickname

'frmElpDisplay.fgData.Row = 19
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_mod_date_time"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_mod_date_time

'frmElpDisplay.fgData.Row = 20
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_verf_oper_nickname"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_verf_oper_nickname

'frmElpDisplay.fgData.Row = 21
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_data_last"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_data_last

'frmElpDisplay.fgData.Row = 22
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_token"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_token

'frmElpDisplay.fgData.Row = 23
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_batch_reference"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_batch_reference

'frmElpDisplay.fgData.Row = 24
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_cas_sender_reference"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_cas_sender_reference

'frmElpDisplay.fgData.Row = 25
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_cas_target_rp_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_cas_target_rp_name

'frmElpDisplay.fgData.Row = 26
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_ccy_amount"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_ccy_amount

'frmElpDisplay.fgData.Row = 27
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_copy_service_id"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_copy_service_id

'frmElpDisplay.fgData.Row = 28
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_data_keyword1"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_data_keyword1

'frmElpDisplay.fgData.Row = 29
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_data_keyword2"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_data_keyword2

'frmElpDisplay.fgData.Row = 30
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_data_keyword3"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_data_keyword3

'frmElpDisplay.fgData.Row = 31
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_delv_overdue_warn_req"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_delv_overdue_warn_req

'frmElpDisplay.fgData.Row = 32
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_fin_ccy_amount"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_fin_ccy_amount

'frmElpDisplay.fgData.Row = 33
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_fin_value_date"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_fin_value_date

'frmElpDisplay.fgData.Row = 34
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_frmt_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_frmt_name

'frmElpDisplay.fgData.Row = 35
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_is_live"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_is_live

'frmElpDisplay.fgData.Row = 36
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_is_retrieved"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_is_retrieved

'frmElpDisplay.fgData.Row = 37
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_mesg_user_group"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_mesg_user_group

'frmElpDisplay.fgData.Row = 38
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_nature"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_nature

'frmElpDisplay.fgData.Row = 39
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_network_appl_ind"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_network_appl_ind

'frmElpDisplay.fgData.Row = 40
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_network_delv_notif_req"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_network_delv_notif_req

'frmElpDisplay.fgData.Row = 41
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_network_obso_period"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_network_obso_period

'frmElpDisplay.fgData.Row = 42
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_network_priority"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_network_priority

'frmElpDisplay.fgData.Row = 43
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_possible_dup_creation"""
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_possible_dup_creation

'frmElpDisplay.fgData.Row = 44
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_receiver_alia_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_receiver_alia_name

'frmElpDisplay.fgData.Row = 45
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_receiver_swift_address"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_receiver_swift_address

'frmElpDisplay.fgData.Row = 46
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_recovery_accept_info"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_recovery_accept_info

'frmElpDisplay.fgData.Row = 47
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_rel_trn_ref"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_rel_trn_ref

'frmElpDisplay.fgData.Row = 48
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_release_info"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_release_info

'frmElpDisplay.fgData.Row = 49
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_security_iapp_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_security_iapp_name

'frmElpDisplay.fgData.Row = 50
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_security_required"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_security_required

'frmElpDisplay.fgData.Row = 51
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_X1"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_X1

'frmElpDisplay.fgData.Row = 52
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_X2"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_X2

'frmElpDisplay.fgData.Row = 53
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_X3"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_X3

'frmElpDisplay.fgData.Row = 54
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_X4"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_X4

'frmElpDisplay.fgData.Row = 55
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_branch_info"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_branch_info

'frmElpDisplay.fgData.Row = 56
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_city_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_city_name

'frmElpDisplay.fgData.Row = 57
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_corr_type"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_corr_type

'frmElpDisplay.fgData.Row = 58
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_ctry_code"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_ctry_code

'frmElpDisplay.fgData.Row = 59
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_ctry_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_ctry_name

'frmElpDisplay.fgData.Row = 60
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_institution_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_institution_name

'frmElpDisplay.fgData.Row = 61
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_location"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_location

'frmElpDisplay.fgData.Row = 62
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sender_swift_address"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sender_swift_address

'frmElpDisplay.fgData.Row = 63
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_sub_format"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_sub_format

'frmElpDisplay.fgData.Row = 64
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_syntax_table_ver"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_syntax_table_ver

'frmElpDisplay.fgData.Row = 65
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_template_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_template_name

'frmElpDisplay.fgData.Row = 66
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_trn_ref"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_trn_ref

'frmElpDisplay.fgData.Row = 67
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_type"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_type

'frmElpDisplay.fgData.Row = 68
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_user_issued_as_pde"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_user_issued_as_pde

'frmElpDisplay.fgData.Row = 69
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_user_priority_code"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_user_priority_code

'frmElpDisplay.fgData.Row = 70
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_user_reference_text"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_user_reference_text

'frmElpDisplay.fgData.Row = 71
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_uumid"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_uumid

'frmElpDisplay.fgData.Row = 72
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_uumid_suffix"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_uumid_suffix

'frmElpDisplay.fgData.Row = 73
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "mesg_zz41_is_possible_dup"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.mesg_zz41_is_possible_dup

'frmElpDisplay.fgData.Row = 74
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_fin_ccy"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_fin_ccy

'frmElpDisplay.fgData.Row = 75
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_fin_amount"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_fin_amount

'frmElpDisplay.fgData.Row = 76
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_fin_value_date"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_fin_value_date

'frmElpDisplay.fgData.Row = 77
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_fin_ocmt_ccy"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_fin_ocmt_ccy

'frmElpDisplay.fgData.Row = 78
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_fin_ocmt_amount"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_fin_ocmt_amount

'frmElpDisplay.fgData.Row = 79
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_own_lt"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_own_lt

'frmElpDisplay.fgData.Row = 80
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_inst0_unit_name"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_inst0_unit_name

'frmElpDisplay.fgData.Row = 81
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_category"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_category

'frmElpDisplay.fgData.Row = 82
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_receiver_X1"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_receiver_X1

'frmElpDisplay.fgData.Row = 83
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_receiver_X2"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_receiver_X2

'frmElpDisplay.fgData.Row = 84
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_receiver_X3"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_receiver_X3

'frmElpDisplay.fgData.Row = 85
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_receiver_X4"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.x_receiver_X4

'frmElpDisplay.fgData.Row = 86
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "archived"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.archived

'frmElpDisplay.fgData.Row = 87
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "last_update"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.last_update

'frmElpDisplay.fgData.Row = 88
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "restored"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.restored

'frmElpDisplay.fgData.Row = 89
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "set_id"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrMesg.set_id

MsgBox "à faire : frmElpDisplay.Show ", vbCritical '  vbModal

End Sub


