Attribute VB_Name = "srvrText"
'---------------------------------------------------------
Option Explicit
'---------------------------------------------------------

Public Const constrText = "rText"

Type typerText
    
    Aid                            As Integer                  ' SAA identification
    text_s_umidl                   As Long                     ' Left part of the internal Swift message reference message)
    text_s_umidh                   As Long                     ' Right part of the internal Swift message reference
    
    text_data_last                 As Long                     '
    text_token                     As Long                     ' CRC on the intervention (generated by SAA)
    text_data_block                As String '* 16             ' Complete text block of the message
    text_swift_block_5             As String '* 1500           ' Block 5 of the message
    text_swift_block_U             As String '* 500            ' Block U of the message
    text_swift_prompted            As String '* 10             '
    text_data_block_len            As Integer                  ' Length of the text block
    x_test_checknum                As Long                     ' CRC on the message text only (generated by SIDE)

End Type

'---------------------------------------------------------
Public Function srvrText_GetBuffer_ODBC(rsADO As ADODB.Recordset, recrText As typerText)
'---------------------------------------------------------
Dim V
On Error GoTo Error_Handler
srvrText_GetBuffer_ODBC = Null

recrText.Aid = rsADO("Aid")
recrText.text_s_umidl = rsADO("text_s_umidl")
recrText.text_s_umidh = rsADO("text_s_umidh")

V = rsADO("text_data_block"): recrText.text_data_block = IIf(IsNull(V), "", V)
V = rsADO("text_data_last"): recrText.text_data_last = IIf(IsNull(V), 0, V)
V = rsADO("text_swift_block_5"): recrText.text_swift_block_5 = IIf(IsNull(V), "", V)
V = rsADO("text_swift_block_U"): recrText.text_swift_block_U = IIf(IsNull(V), "", V)
V = rsADO("text_swift_prompted"): recrText.text_swift_prompted = IIf(IsNull(V), "", V)

recrText.text_token = rsADO("text_token")
recrText.text_data_block_len = rsADO("text_data_block_len")
'$JPL 2013-12-26 recrText.x_test_checknum = rsADO("x_test_checknum")

Exit Function

Error_Handler:
srvrText_GetBuffer_ODBC = Error

End Function

'---------------------------------------------------------
Public Sub srvrText_Init(recrText As typerText)
'---------------------------------------------------------

recrText.Aid = 0
recrText.text_s_umidl = 0
recrText.text_s_umidh = 0

recrText.text_data_last = 0
recrText.text_token = 0
recrText.text_data_block = ""
recrText.text_swift_block_5 = ""
recrText.text_swift_block_U = ""
recrText.text_swift_prompted = ""
recrText.text_data_block_len = 0
recrText.x_test_checknum = 0

End Sub

'---------------------------------------------------------
Public Sub srvrText_ElpDisplay(recrText As typerText)
'---------------------------------------------------------
'frmElpDisplay.fgData.Rows = 12

'frmElpDisplay.fgData.Row = 1
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "Aid"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrText.Aid

'frmElpDisplay.fgData.Row = 2
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "text_s_umidl"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrText.text_s_umidl

'frmElpDisplay.fgData.Row = 3
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "text_s_umidh"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrText.text_s_umidh

'frmElpDisplay.fgData.Row = 4
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "text_data_last"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrText.text_data_last

'frmElpDisplay.fgData.Row = 5
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "text_token"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrText.text_token

'frmElpDisplay.fgData.Row = 6
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "text_data_block"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrText.text_data_block

'frmElpDisplay.fgData.Row = 7
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "text_swift_block_5"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrText.text_swift_block_5

'frmElpDisplay.fgData.Row = 8
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "text_swift_block_U"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrText.text_swift_block_U

'frmElpDisplay.fgData.Row = 9
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "text_swift_prompted"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrText.text_swift_prompted

'frmElpDisplay.fgData.Row = 10
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "text_data_block_len"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrText.text_data_block_len

'frmElpDisplay.fgData.Row = 11
'frmElpDisplay.fgData.Col = 0: frmElpDisplay.fgData = "x_test_checknum"
'frmElpDisplay.fgData.Col = 1: frmElpDisplay.fgData = ""
'frmElpDisplay.fgData.Col = 2: frmElpDisplay.fgData = recrText.x_test_checknum

MsgBox "à faire : frmElpDisplay.Show ", vbCritical '  vbModal

End Sub



