Attribute VB_Name = "adoYAUTE1I0"
'---------------------------------------------------------
Option Explicit
'---------------------------------------------------------
'---------------------------------------------------------
Public Function rsYAUTE1I0_PutBuffer(rsADO As ADODB.Recordset, rsYAUTE1I0 As typeYAUTE1I0)
'---------------------------------------------------------
On Error GoTo Error_Handler
rsYAUTE1I0_PutBuffer = Null

 
rsADO("AUTE1IETA") = rsYAUTE1I0.AUTE1IETA
rsADO("AUTE1IGRP") = rsYAUTE1I0.AUTE1IGRP
rsADO("AUTE1ICLI") = rsYAUTE1I0.AUTE1ICLI
rsADO("AUTE1ITYP") = rsYAUTE1I0.AUTE1ITYP
rsADO("AUTE1IAUT") = rsYAUTE1I0.AUTE1IAUT
rsADO("AUTE1IDEV") = rsYAUTE1I0.AUTE1IDEV
rsADO("AUTE1IAGE") = rsYAUTE1I0.AUTE1IAGE
rsADO("AUTE1ISER") = rsYAUTE1I0.AUTE1ISER
rsADO("AUTE1ISRV") = rsYAUTE1I0.AUTE1ISRV
rsADO("AUTE1ICOP") = rsYAUTE1I0.AUTE1ICOP
rsADO("AUTE1INOP") = rsYAUTE1I0.AUTE1INOP
rsADO("AUTE1IOR1") = rsYAUTE1I0.AUTE1IOR1
rsADO("AUTE1IOR2") = rsYAUTE1I0.AUTE1IOR2
rsADO("AUTE1IOR3") = rsYAUTE1I0.AUTE1IOR3
rsADO("AUTE1IOR4") = rsYAUTE1I0.AUTE1IOR4
rsADO("AUTE1IDBA") = rsYAUTE1I0.AUTE1IDBA
rsADO("AUTE1IMDB") = rsYAUTE1I0.AUTE1IMDB
rsADO("AUTE1IMCR") = rsYAUTE1I0.AUTE1IMCR
rsADO("AUTE1IBDB") = rsYAUTE1I0.AUTE1IBDB
rsADO("AUTE1IBCR") = rsYAUTE1I0.AUTE1IBCR
rsADO("AUTE1IRDB") = rsYAUTE1I0.AUTE1IRDB
rsADO("AUTE1IRCR") = rsYAUTE1I0.AUTE1IRCR
rsADO("AUTE1IMAU") = rsYAUTE1I0.AUTE1IMAU
rsADO("AUTE1IDAD") = rsYAUTE1I0.AUTE1IDAD
rsADO("AUTE1IDAF") = rsYAUTE1I0.AUTE1IDAF
rsADO("AUTE1IINT") = rsYAUTE1I0.AUTE1IINT
rsADO("AUTE1IDMO") = rsYAUTE1I0.AUTE1IDMO
rsADO("AUTE1IRA1") = rsYAUTE1I0.AUTE1IRA1
rsADO("AUTE1IRA2") = rsYAUTE1I0.AUTE1IRA2
rsADO("AUTE1ISAC") = rsYAUTE1I0.AUTE1ISAC
rsADO("AUTE1IREG") = rsYAUTE1I0.AUTE1IREG
rsADO("AUTE1ISRN") = rsYAUTE1I0.AUTE1ISRN
rsADO("AUTE1IRES") = rsYAUTE1I0.AUTE1IRES
rsADO("AUTE1IECO") = rsYAUTE1I0.AUTE1IECO
rsADO("AUTE1ICOT") = rsYAUTE1I0.AUTE1ICOT
rsADO("AUTE1IBDF") = rsYAUTE1I0.AUTE1IBDF
rsADO("AUTE1IDOU") = rsYAUTE1I0.AUTE1IDOU
rsADO("AUTE1IICH") = rsYAUTE1I0.AUTE1IICH
rsADO("AUTE1ICET") = rsYAUTE1I0.AUTE1ICET
rsADO("AUTE1ISIG") = rsYAUTE1I0.AUTE1ISIG
rsADO("AUTE1IRAG") = rsYAUTE1I0.AUTE1IRAG
rsADO("AUTE1IELM") = rsYAUTE1I0.AUTE1IELM
rsADO("AUTE1INIV") = rsYAUTE1I0.AUTE1INIV
rsADO("AUTE1IBLO") = rsYAUTE1I0.AUTE1IBLO
rsADO("AUTE1ICOM") = rsYAUTE1I0.AUTE1ICOM
rsADO("AUTE1ILAU") = rsYAUTE1I0.AUTE1ILAU
rsADO("AUTE1IECI") = rsYAUTE1I0.AUTE1IECI
rsADO("AUTE1IDEP") = rsYAUTE1I0.AUTE1IDEP
rsADO("AUTE1IMTD") = rsYAUTE1I0.AUTE1IMTD
rsADO("AUTE1IDPD") = rsYAUTE1I0.AUTE1IDPD
rsADO("AUTE1IDTD") = rsYAUTE1I0.AUTE1IDTD
rsADO("AUTE1IC1A") = rsYAUTE1I0.AUTE1IC1A
rsADO("AUTE1IDEB") = rsYAUTE1I0.AUTE1IDEB
rsADO("AUTE1IFIN") = rsYAUTE1I0.AUTE1IFIN
rsADO("AUTE1ILIB") = rsYAUTE1I0.AUTE1ILIB
rsADO("AUTE1IRAT") = rsYAUTE1I0.AUTE1IRAT
rsADO("AUTE1IATR") = rsYAUTE1I0.AUTE1IATR
rsADO("AUTE1IREL") = rsYAUTE1I0.AUTE1IREL
rsADO("AUTE1IRUB") = rsYAUTE1I0.AUTE1IRUB
rsADO("AUTE1IAGC") = rsYAUTE1I0.AUTE1IAGC
rsADO("AUTE1ISEG") = rsYAUTE1I0.AUTE1ISEG
rsADO("AUTE1ISEP") = rsYAUTE1I0.AUTE1ISEP
rsADO("AUTE1IFUT") = rsYAUTE1I0.AUTE1IFUT
   
Exit Function

Error_Handler:

rsYAUTE1I0_PutBuffer = Error

End Function


'---------------------------------------------------------
Public Function adoYAUTE1I0_AddNew(rsADO As ADODB.Recordset, rsYAUTE1I0 As typeYAUTE1I0)
'---------------------------------------------------------
On Error GoTo Error_Handler

adoYAUTE1I0_AddNew = Null
rsADO.AddNew
adoYAUTE1I0_AddNew = rsYAUTE1I0_PutBuffer(rsADO, rsYAUTE1I0)
rsADO.Update

Exit Function

Error_Handler:

adoYAUTE1I0_AddNew = Error

End Function

