Attribute VB_Name = "adoYBIACPT0"
'---------------------------------------------------------
Option Explicit
'---------------------------------------------------------
'---------------------------------------------------------
Public Function rsYBIACPT0_PutBuffer(rsADO As ADODB.Recordset, rsYBIACPT0 As typeYBIACPT0)
'---------------------------------------------------------
On Error GoTo Error_Handler
rsYBIACPT0_PutBuffer = Null

rsADO("COMPTEETA") = rsYBIACPT0.COMPTEETA
rsADO("COMPTEPLA") = rsYBIACPT0.COMPTEPLA
rsADO("COMPTECOM") = rsYBIACPT0.COMPTECOM
rsADO("COMPTEOBL") = rsYBIACPT0.COMPTEOBL
rsADO("COMPTEINT") = rsYBIACPT0.COMPTEINT
rsADO("COMPTEAGE") = rsYBIACPT0.COMPTEAGE
rsADO("COMPTEDEV") = rsYBIACPT0.COMPTEDEV
rsADO("COMPTEOUV") = rsYBIACPT0.COMPTEOUV
rsADO("COMPTECLO") = rsYBIACPT0.COMPTECLO
rsADO("COMPTELOR") = rsYBIACPT0.COMPTELOR
rsADO("COMPTESUC") = rsYBIACPT0.COMPTESUC
rsADO("COMPTECLA") = rsYBIACPT0.COMPTECLA
rsADO("COMPTEFON") = rsYBIACPT0.COMPTEFON
rsADO("COMPTEBLO") = rsYBIACPT0.COMPTEBLO
rsADO("COMPTEMOT") = rsYBIACPT0.COMPTEMOT
rsADO("COMPTESEN") = rsYBIACPT0.COMPTESEN
rsADO("COMPTEMOD") = rsYBIACPT0.COMPTEMOD

rsADO("CLIENAETB") = rsYBIACPT0.CLIENAETB
rsADO("CLIENACLI") = rsYBIACPT0.CLIENACLI
rsADO("CLIENAAGE") = rsYBIACPT0.CLIENAAGE
rsADO("CLIENAETA") = rsYBIACPT0.CLIENAETA
rsADO("CLIENARA1") = rsYBIACPT0.CLIENARA1
rsADO("CLIENARA2") = rsYBIACPT0.CLIENARA2
rsADO("CLIENASIG") = rsYBIACPT0.CLIENASIG
rsADO("CLIENASRN") = rsYBIACPT0.CLIENASRN
rsADO("CLIENASRT") = rsYBIACPT0.CLIENASRT
rsADO("CLIENADNA") = rsYBIACPT0.CLIENADNA
rsADO("CLIENAREG") = rsYBIACPT0.CLIENAREG
rsADO("CLIENANAT") = rsYBIACPT0.CLIENANAT
rsADO("CLIENARSD") = rsYBIACPT0.CLIENARSD
rsADO("CLIENARES") = rsYBIACPT0.CLIENARES
rsADO("CLIENAECO") = rsYBIACPT0.CLIENAECO
rsADO("CLIENAACT") = rsYBIACPT0.CLIENAACT
rsADO("CLIENAPAI") = rsYBIACPT0.CLIENAPAI
rsADO("CLIENACRD") = rsYBIACPT0.CLIENACRD
rsADO("CLIENAADM") = rsYBIACPT0.CLIENAADM
rsADO("CLIENAATR") = rsYBIACPT0.CLIENAATR
rsADO("CLIENABIL") = rsYBIACPT0.CLIENABIL
rsADO("CLIENACAT") = rsYBIACPT0.CLIENACAT
rsADO("CLIENACOT") = rsYBIACPT0.CLIENACOT
rsADO("CLIENACHQ") = rsYBIACPT0.CLIENACHQ
rsADO("CLIENADAT") = rsYBIACPT0.CLIENADAT
rsADO("CLIENASAC") = rsYBIACPT0.CLIENASAC
rsADO("CLIENAGEO") = rsYBIACPT0.CLIENAGEO
rsADO("CLIENAENT") = rsYBIACPT0.CLIENAENT
rsADO("CLIENAMES") = rsYBIACPT0.CLIENAMES
rsADO("CLIENAPAY") = rsYBIACPT0.CLIENAPAY
rsADO("CLIENAFIL") = rsYBIACPT0.CLIENAFIL
rsADO("CLIENABIM") = rsYBIACPT0.CLIENABIM
rsADO("CLIENADOU") = rsYBIACPT0.CLIENADOU
rsADO("CLIENALI1") = rsYBIACPT0.CLIENALI1
rsADO("CLIENALI2") = rsYBIACPT0.CLIENALI2
rsADO("CLIENAEXT") = rsYBIACPT0.CLIENAEXT
rsADO("CLIENACOL") = rsYBIACPT0.CLIENACOL
rsADO("CLIENATIE") = rsYBIACPT0.CLIENATIE
rsADO("CLIENASEL") = rsYBIACPT0.CLIENASEL
rsADO("CLIENAPCS") = rsYBIACPT0.CLIENAPCS
rsADO("CLIENACRE") = rsYBIACPT0.CLIENACRE

rsADO("PLANCOPRO") = rsYBIACPT0.PLANCOPRO
rsADO("SOLDEDMO") = rsYBIACPT0.SOLDEDMO
rsADO("SOLDECEN") = rsYBIACPT0.SOLDECEN * 1000
rsADO("COMREFREF") = rsYBIACPT0.COMREFREF
rsADO("TITULACLI") = rsYBIACPT0.TITULACLI
rsADO("TITULAPRI") = rsYBIACPT0.TITULAPRI
rsADO("TITULATPR") = rsYBIACPT0.TITULATPR
    
Exit Function

Error_Handler:

rsYBIACPT0_PutBuffer = Error

End Function


'---------------------------------------------------------
Public Function adoYBIACPT0_AddNew(rsADO As ADODB.Recordset, rsYBIACPT0 As typeYBIACPT0)
'---------------------------------------------------------
On Error GoTo Error_Handler

adoYBIACPT0_AddNew = Null
rsADO.AddNew
adoYBIACPT0_AddNew = rsYBIACPT0_PutBuffer(rsADO, rsYBIACPT0)
rsADO.Update

Exit Function

Error_Handler:

adoYBIACPT0_AddNew = Error

End Function
'---------------------------------------------------------
Public Function adoYBIACPT0_Update(rsADO As ADODB.Recordset, rsYBIACPT0 As typeYBIACPT0)
'---------------------------------------------------------
Dim xSql As String

On Error GoTo Error_Handler
adoYBIACPT0_Update = "? rsYBIACPT0_AddNew"

xSql = "Select * from YBIACPT0 where COMPTECOM = '" & rsYBIACPT0.COMPTECOM & "'"

rsADO.Open xSql, paramODBC_DSN_SAB073Y, adOpenDynamic, adLockOptimistic
If Not rsADO.EOF Then
   ''Call rsYBIACPT0_GetBuffer(rsADO, rsYBIACPT0)
    rsADO("COMPTEOBL") = "MODIFIE"
    rsADO.Update
    adoYBIACPT0_Update = Null
Else
    adoYBIACPT0_Update = "? " & rsYBIACPT0.COMPTECOM
End If
    
rsADO.Close

Exit Function

Error_Handler:

adoYBIACPT0_Update = Error

End Function



