Attribute VB_Name = "adoZCDOUTI0"
'---------------------------------------------------------
Option Explicit
'---------------------------------------------------------

Public Function rsZCDOUTI0_PutBuffer(rsADO As ADODB.Recordset, rsZCDOUTI0 As typeZCDOUTI0)
On Error GoTo Error_Handler
rsZCDOUTI0_PutBuffer = Null
rsADO("CDOUTIETB") = rsZCDOUTI0.CDOUTIETB
rsADO("CDOUTIAGE") = rsZCDOUTI0.CDOUTIAGE
rsADO("CDOUTISER") = rsZCDOUTI0.CDOUTISER
rsADO("CDOUTISSE") = rsZCDOUTI0.CDOUTISSE
rsADO("CDOUTICOP") = rsZCDOUTI0.CDOUTICOP
rsADO("CDOUTIDOS") = rsZCDOUTI0.CDOUTIDOS
rsADO("CDOUTINUR") = rsZCDOUTI0.CDOUTINUR
rsADO("CDOUTIUTI") = rsZCDOUTI0.CDOUTIUTI
rsADO("CDOUTITMO") = rsZCDOUTI0.CDOUTITMO
rsADO("CDOUTIMON") = rsZCDOUTI0.CDOUTIMON
rsADO("CDOUTIMAD") = rsZCDOUTI0.CDOUTIMAD
rsADO("CDOUTIMTO") = rsZCDOUTI0.CDOUTIMTO
rsADO("CDOUTIMDO") = rsZCDOUTI0.CDOUTIMDO
rsADO("CDOUTIMPA") = rsZCDOUTI0.CDOUTIMPA
rsADO("CDOUTIPRE") = rsZCDOUTI0.CDOUTIPRE
rsADO("CDOUTIDAR") = rsZCDOUTI0.CDOUTIDAR
rsADO("CDOUTIOBJ") = rsZCDOUTI0.CDOUTIOBJ
rsADO("CDOUTIMVU") = rsZCDOUTI0.CDOUTIMVU
rsADO("CDOUTIMCA") = rsZCDOUTI0.CDOUTIMCA
rsADO("CDOUTIMDI") = rsZCDOUTI0.CDOUTIMDI
rsADO("CDOUTICTR") = rsZCDOUTI0.CDOUTICTR
rsADO("CDOUTIREM") = rsZCDOUTI0.CDOUTIREM
rsADO("CDOUTIRER") = rsZCDOUTI0.CDOUTIRER
rsADO("CDOUTIDRE") = rsZCDOUTI0.CDOUTIDRE
rsADO("CDOUTIDCO") = rsZCDOUTI0.CDOUTIDCO
rsADO("CDOUTIDCE") = rsZCDOUTI0.CDOUTIDCE
rsADO("CDOUTIRET") = rsZCDOUTI0.CDOUTIRET
rsADO("CDOUTIDAC") = rsZCDOUTI0.CDOUTIDAC
rsADO("CDOUTIPAR") = rsZCDOUTI0.CDOUTIPAR
rsADO("CDOUTIIRR") = rsZCDOUTI0.CDOUTIIRR
rsADO("CDOUTIPOR") = rsZCDOUTI0.CDOUTIPOR
rsADO("CDOUTIREF") = rsZCDOUTI0.CDOUTIREF
rsADO("CDOUTIESC") = rsZCDOUTI0.CDOUTIESC
rsADO("CDOUTIBEC") = rsZCDOUTI0.CDOUTIBEC
rsADO("CDOUTIVA1") = rsZCDOUTI0.CDOUTIVA1
rsADO("CDOUTIVA2") = rsZCDOUTI0.CDOUTIVA2
rsADO("CDOUTIEVE") = rsZCDOUTI0.CDOUTIEVE
rsADO("CDOUTIATT") = rsZCDOUTI0.CDOUTIATT
rsADO("CDOUTIETA") = rsZCDOUTI0.CDOUTIETA
Exit Function
Error_Handler:
rsZCDOUTI0_PutBuffer = Error
End Function

'---------------------------------------------------------
Public Function adoZCDOUTI0_AddNew(rsADO As ADODB.Recordset, rsZCDOUTI0 As typeZCDOUTI0)
'---------------------------------------------------------
On Error GoTo Error_Handler

adoZCDOUTI0_AddNew = Null
rsADO.AddNew
adoZCDOUTI0_AddNew = rsZCDOUTI0_PutBuffer(rsADO, rsZCDOUTI0)
rsADO.Update

Exit Function

Error_Handler:

adoZCDOUTI0_AddNew = Error

End Function


