Attribute VB_Name = "adoZCDODOS0"
'---------------------------------------------------------
Option Explicit
'---------------------------------------------------------
'---------------------------------------------------------
Public Function rsZCDODOS0_PutBuffer(rsADO As ADODB.Recordset, rsZCDODOS0 As typeZCDODOS0)
'---------------------------------------------------------
On Error GoTo Error_Handler
rsZCDODOS0_PutBuffer = Null

'''rsado("CDODOSETB")") = rsZCDODOS0.CDODOSETB
rsADO("CDODOSETB") = rsZCDODOS0.CDODOSETB
rsADO("CDODOSAGE") = rsZCDODOS0.CDODOSAGE
rsADO("CDODOSSER") = rsZCDODOS0.CDODOSSER
rsADO("CDODOSSSE") = rsZCDODOS0.CDODOSSSE
rsADO("CDODOSCOP") = rsZCDODOS0.CDODOSCOP
rsADO("CDODOSDOS") = rsZCDODOS0.CDODOSDOS
rsADO("CDODOSNUR") = rsZCDODOS0.CDODOSNUR
rsADO("CDODOSNAT") = rsZCDODOS0.CDODOSNAT
rsADO("CDODOSEXT") = rsZCDODOS0.CDODOSEXT
rsADO("CDODOSMON") = rsZCDODOS0.CDODOSMON
rsADO("CDODOSDEV") = rsZCDODOS0.CDODOSDEV
rsADO("CDODOSMOA") = rsZCDODOS0.CDODOSMOA
rsADO("CDODOSMOT") = rsZCDODOS0.CDODOSMOT
rsADO("CDODOSMOC") = rsZCDODOS0.CDODOSMOC
rsADO("CDODOSMOD") = rsZCDODOS0.CDODOSMOD
rsADO("CDODOSCON") = rsZCDODOS0.CDODOSCON
rsADO("CDODOSIRR") = rsZCDODOS0.CDODOSIRR
rsADO("CDODOSFRA") = rsZCDODOS0.CDODOSFRA
rsADO("CDODOSREN") = rsZCDODOS0.CDODOSREN
rsADO("CDODOSCUM") = rsZCDODOS0.CDODOSCUM
rsADO("CDODOSTRS") = rsZCDODOS0.CDODOSTRS
rsADO("CDODOSTOL") = rsZCDODOS0.CDODOSTOL
rsADO("CDODOSTO2") = rsZCDODOS0.CDODOSTO2
rsADO("CDODOSDOR") = rsZCDODOS0.CDODOSDOR
rsADO("CDODOSDON") = rsZCDODOS0.CDODOSDON
rsADO("CDODOSDOE") = rsZCDODOS0.CDODOSDOE
rsADO("CDODOSBER") = rsZCDODOS0.CDODOSBER
rsADO("CDODOSBEN") = rsZCDODOS0.CDODOSBEN
rsADO("CDODOSBEI") = rsZCDODOS0.CDODOSBEI
rsADO("CDODOSBAR") = rsZCDODOS0.CDODOSBAR
rsADO("CDODOSBAB") = rsZCDODOS0.CDODOSBAB
rsADO("CDODOSNOR") = rsZCDODOS0.CDODOSNOR
rsADO("CDODOSNOT") = rsZCDODOS0.CDODOSNOT
rsADO("CDODOSBIC") = rsZCDODOS0.CDODOSBIC
rsADO("CDODOSCOT") = rsZCDODOS0.CDODOSCOT
rsADO("CDODOSCOR") = rsZCDODOS0.CDODOSCOR
rsADO("CDODOSPRT") = rsZCDODOS0.CDODOSPRT
rsADO("CDODOSPRR") = rsZCDODOS0.CDODOSPRR
rsADO("CDODOSUTV") = rsZCDODOS0.CDODOSUTV
rsADO("CDODOSPAT") = rsZCDODOS0.CDODOSPAT
rsADO("CDODOSPAR") = rsZCDODOS0.CDODOSPAR
rsADO("CDODOSPAV") = rsZCDODOS0.CDODOSPAV
rsADO("CDODOSOUV") = rsZCDODOS0.CDODOSOUV
rsADO("CDODOSEMI") = rsZCDODOS0.CDODOSEMI
rsADO("CDODOSVAL") = rsZCDODOS0.CDODOSVAL
rsADO("CDODOSDEP") = rsZCDODOS0.CDODOSDEP
rsADO("CDODOSDTR") = rsZCDODOS0.CDODOSDTR
rsADO("CDODOSVCP") = rsZCDODOS0.CDODOSVCP
rsADO("CDODOSCLO") = rsZCDODOS0.CDODOSCLO
rsADO("CDODOSREJ") = rsZCDODOS0.CDODOSREJ
rsADO("CDODOSOBJ") = rsZCDODOS0.CDODOSOBJ
rsADO("CDODOSAVU") = rsZCDODOS0.CDODOSAVU
rsADO("CDODOSMOV") = rsZCDODOS0.CDODOSMOV
rsADO("CDODOSCAC") = rsZCDODOS0.CDODOSCAC
rsADO("CDODOSMCA") = rsZCDODOS0.CDODOSMCA
rsADO("CDODOSDIF") = rsZCDODOS0.CDODOSDIF
rsADO("CDODOSMDI") = rsZCDODOS0.CDODOSMDI
rsADO("CDODOSPMO") = rsZCDODOS0.CDODOSPMO
rsADO("CDODOSPCD") = rsZCDODOS0.CDODOSPCD
rsADO("CDODOSPCC") = rsZCDODOS0.CDODOSPCC
rsADO("CDODOSPDE") = rsZCDODOS0.CDODOSPDE
rsADO("CDODOSPPO") = rsZCDODOS0.CDODOSPPO
rsADO("CDODOSAUT") = rsZCDODOS0.CDODOSAUT
rsADO("CDODOSREG") = rsZCDODOS0.CDODOSREG
rsADO("CDODOSENC") = rsZCDODOS0.CDODOSENC
rsADO("CDODOSDAN") = rsZCDODOS0.CDODOSDAN
rsADO("CDODOSANN") = rsZCDODOS0.CDODOSANN
rsADO("CDODOSPCO") = rsZCDODOS0.CDODOSPCO
rsADO("CDODOSLEM") = rsZCDODOS0.CDODOSLEM
rsADO("CDODOSLDE") = rsZCDODOS0.CDODOSLDE
rsADO("CDODOSDLE") = rsZCDODOS0.CDODOSDLE
rsADO("CDODOSEPA") = rsZCDODOS0.CDODOSEPA
rsADO("CDODOSTRA") = rsZCDODOS0.CDODOSTRA
rsADO("CDODOSFCD") = rsZCDODOS0.CDODOSFCD
rsADO("CDODOSCUS") = rsZCDODOS0.CDODOSCUS
rsADO("CDODOSCUV") = rsZCDODOS0.CDODOSCUV
rsADO("CDODOSCU2") = rsZCDODOS0.CDODOSCU2
rsADO("CDODOSOPE") = rsZCDODOS0.CDODOSOPE
rsADO("CDODOSPOO") = rsZCDODOS0.CDODOSPOO
rsADO("CDODOSPBE") = rsZCDODOS0.CDODOSPBE
rsADO("CDODOSGAG") = rsZCDODOS0.CDODOSGAG
rsADO("CDODOSSTB") = rsZCDODOS0.CDODOSSTB
rsADO("CDODOSMRE") = rsZCDODOS0.CDODOSMRE
rsADO("CDODOSNPD") = rsZCDODOS0.CDODOSNPD
rsADO("CDODOSTJD") = rsZCDODOS0.CDODOSTJD
rsADO("CDODOSPDO") = rsZCDODOS0.CDODOSPDO
rsADO("CDODOSGAR") = rsZCDODOS0.CDODOSGAR
rsADO("CDODOSOBM") = rsZCDODOS0.CDODOSOBM
rsADO("CDODOSTBR") = rsZCDODOS0.CDODOSTBR
rsADO("CDODOSBRE") = rsZCDODOS0.CDODOSBRE
rsADO("CDODOSBEC") = rsZCDODOS0.CDODOSBEC
rsADO("CDODOSRNO") = rsZCDODOS0.CDODOSRNO
rsADO("CDODOSDPA") = rsZCDODOS0.CDODOSDPA
rsADO("CDODOSDVI") = rsZCDODOS0.CDODOSDVI
rsADO("CDODOSEPY") = rsZCDODOS0.CDODOSEPY
rsADO("CDODOSEVI") = rsZCDODOS0.CDODOSEVI
rsADO("CDODOSVPA") = rsZCDODOS0.CDODOSVPA
rsADO("CDODOSVVI") = rsZCDODOS0.CDODOSVVI
rsADO("CDODOSNDE") = rsZCDODOS0.CDODOSNDE
rsADO("CDODOSNAE") = rsZCDODOS0.CDODOSNAE
rsADO("CDODOSEVE") = rsZCDODOS0.CDODOSEVE
rsADO("CDODOSETA") = rsZCDODOS0.CDODOSETA
rsADO("CDODOSDP2") = rsZCDODOS0.CDODOSDP2
rsADO("CDODOSEP2") = rsZCDODOS0.CDODOSEP2
rsADO("CDODOSPD2") = rsZCDODOS0.CDODOSPD2
rsADO("CDODOSAUN") = rsZCDODOS0.CDODOSAUN
rsADO("CDODOSCER") = rsZCDODOS0.CDODOSCER
rsADO("CDODOSCRE") = rsZCDODOS0.CDODOSCRE
rsADO("CDODOSREM") = rsZCDODOS0.CDODOSREM
rsADO("CDODOSRGR") = rsZCDODOS0.CDODOSRGR
rsADO("CDODOSLED") = rsZCDODOS0.CDODOSLED
rsADO("CDODOSLDA") = rsZCDODOS0.CDODOSLDA
  
Exit Function

Error_Handler:

rsZCDODOS0_PutBuffer = Error

End Function


'---------------------------------------------------------
Public Function adoZCDODOS0_AddNew(rsADO As ADODB.Recordset, rsZCDODOS0 As typeZCDODOS0)
'---------------------------------------------------------
On Error GoTo Error_Handler

adoZCDODOS0_AddNew = Null
rsADO.AddNew
adoZCDODOS0_AddNew = rsZCDODOS0_PutBuffer(rsADO, rsZCDODOS0)
rsADO.Update

Exit Function

Error_Handler:

adoZCDODOS0_AddNew = Error

End Function

