Attribute VB_Name = "rszENCCAR0"
Option Explicit

Type typeZENCCAR0
    ENCCARETA       As Integer                        'code établissement
    ENCCARAGE       As Integer                        ' AGENCE
    ENCCARSER       As String * 2                     ' SERVICE
    ENCCARSSE       As String * 2                     ' SOUS-SERVICE
    ENCCARCOP       As String * 3                     ' CODE OPERATION
    ENCCARDOS       As Long                           ' NUMERO DOSSIER
    ENCCARNAT       As String * 3                     'code nature
    ENCCAROBJ       As String * 6
    ENCCARTYD       As String * 4
    ENCCARTYR       As String * 4
    ENCCARCPR       As String * 4
    ENCCARREX       As String * 16
    ENCCARRCL       As String * 16
    ENCCARORD       As String * 8
    ENCCARTIR       As String * 8
    ENCCARINT       As String * 8
    ENCCARBES       As String * 8
    ENCCARBQE       As String * 8
    ENCCARAVA       As String * 1
    ENCCARBAV       As String * 8
    ENCCARCOR       As String * 8
    ENCCARDPA       As String * 1
    ENCCARABA       As String * 1
    ENCCARPPA       As String * 1
    ENCCARMON       As Currency
    ENCCARDEV       As String * 3
    ENCCARAUT       As String * 12
    ENCCARTP1       As String * 3
    ENCCARMO1       As Currency
    ENCCAREC1       As Long
    ENCCARPE1       As String * 1
    ENCCARNJ1       As String * 3
    ENCCARCP1       As String * 2
    ENCCARTP2       As String * 3
    ENCCARMO2       As Currency
    ENCCAREC2       As Long
    ENCCARPE2       As String * 1
    ENCCARNJ2       As String * 3
    ENCCARCP2       As String * 2
    ENCCARTP3       As String * 3
    ENCCARMO3       As Currency
    ENCCAREC3       As Long
    ENCCARPE3       As String * 1
    ENCCARNJ3       As String * 3
    ENCCARCP3       As String * 2
    ENCCARFRC       As Currency
    ENCCARABF       As String * 1
    ENCCARTXI       As Currency
    ENCCARPER       As String * 1
    ENCCARPEJ       As Long
    ENCCARBAS       As Long
    ENCCARDDI       As Long
    ENCCARABI       As String * 1
    ENCCARDAR       As Long
    ENCCARDAM       As Long
    ENCCARDAC       As Long
    ENCCARDSU       As Long
    ENCCARDRV       As Long
    ENCCARDRE       As Long
    ENCCARDRC       As Long
    ENCCARCET       As String * 2
    ENCCARCEA       As String * 1
    ENCCARDRA       As Long
    ENCCARPES       As Long
    ENCCARNCH       As Long
    ENCCARRSI       As String * 1
    ENCCARUEN       As Integer
    ENCCARUL1       As Integer
    ENCCARUL2       As Integer
    ENCCARSWI       As String * 1
    ENCCARDR1       As Currency
    ENCCARDR2       As Currency
    ENCCARDR3       As Currency
End Type
Public Function rsZENCCAR0_GetBuffer(rsADO As ADODB.Recordset, rsZENCCAR0 As typeZENCCAR0)

    rsZENCCAR0_GetBuffer = Null
    rsZENCCAR0.ENCCARETA = rsADO("ENCCARETA")
    rsZENCCAR0.ENCCARAGE = rsADO("ENCCARAGE")
    rsZENCCAR0.ENCCARSER = rsADO("ENCCARSER")
    rsZENCCAR0.ENCCARSSE = rsADO("ENCCARSSE")
    rsZENCCAR0.ENCCARCOP = rsADO("ENCCARCOP")
    rsZENCCAR0.ENCCARDOS = rsADO("ENCCARDOS")
    rsZENCCAR0.ENCCARNAT = rsADO("ENCCARNAT")
    rsZENCCAR0.ENCCAROBJ = rsADO("ENCCAROBJ")
    rsZENCCAR0.ENCCARTYD = rsADO("ENCCARTYD")
    rsZENCCAR0.ENCCARTYR = rsADO("ENCCARTYR")
    rsZENCCAR0.ENCCARCPR = rsADO("ENCCARCPR")
    rsZENCCAR0.ENCCARREX = rsADO("ENCCARREX")
    rsZENCCAR0.ENCCARRCL = rsADO("ENCCARRCL")
    rsZENCCAR0.ENCCARORD = rsADO("ENCCARORD")
    rsZENCCAR0.ENCCARTIR = rsADO("ENCCARTIR")
    rsZENCCAR0.ENCCARINT = rsADO("ENCCARINT")
    rsZENCCAR0.ENCCARBES = rsADO("ENCCARBES")
    rsZENCCAR0.ENCCARBQE = rsADO("ENCCARBQE")
    rsZENCCAR0.ENCCARAVA = rsADO("ENCCARAVA")
    rsZENCCAR0.ENCCARBAV = rsADO("ENCCARBAV")
    rsZENCCAR0.ENCCARCOR = rsADO("ENCCARCOR")
    rsZENCCAR0.ENCCARDPA = rsADO("ENCCARDPA")
    rsZENCCAR0.ENCCARABA = rsADO("ENCCARABA")
    rsZENCCAR0.ENCCARPPA = rsADO("ENCCARPPA")
    rsZENCCAR0.ENCCARMON = rsADO("ENCCARMON")
    rsZENCCAR0.ENCCARDEV = rsADO("ENCCARDEV")
    rsZENCCAR0.ENCCARAUT = rsADO("ENCCARAUT")
    rsZENCCAR0.ENCCARTP1 = rsADO("ENCCARTP1")
    rsZENCCAR0.ENCCARMO1 = rsADO("ENCCARMO1")
    rsZENCCAR0.ENCCAREC1 = rsADO("ENCCAREC1")
    rsZENCCAR0.ENCCARPE1 = rsADO("ENCCARPE1")
    rsZENCCAR0.ENCCARNJ1 = rsADO("ENCCARNJ1")
    rsZENCCAR0.ENCCARCP1 = rsADO("ENCCARCP1")
    rsZENCCAR0.ENCCARCP2 = rsADO("ENCCARCP2")
    rsZENCCAR0.ENCCARMO2 = rsADO("ENCCARMO2")
    rsZENCCAR0.ENCCAREC2 = rsADO("ENCCAREC2")
    rsZENCCAR0.ENCCARPE2 = rsADO("ENCCARPE2")
    rsZENCCAR0.ENCCARNJ2 = rsADO("ENCCARNJ2")
    rsZENCCAR0.ENCCARCP2 = rsADO("ENCCARCP2")
    rsZENCCAR0.ENCCARTP3 = rsADO("ENCCARTP3")
    rsZENCCAR0.ENCCARMO3 = rsADO("ENCCARMO3")
    rsZENCCAR0.ENCCAREC3 = rsADO("ENCCAREC3")
    rsZENCCAR0.ENCCARPE3 = rsADO("ENCCARPE3")
    rsZENCCAR0.ENCCARNJ3 = rsADO("ENCCARNJ3")
    rsZENCCAR0.ENCCARCP3 = rsADO("ENCCARCP3")
    rsZENCCAR0.ENCCARFRC = rsADO("ENCCARFRC")
    rsZENCCAR0.ENCCARABF = rsADO("ENCCARABF")
    rsZENCCAR0.ENCCARTXI = rsADO("ENCCARTXI")
    rsZENCCAR0.ENCCARPER = rsADO("ENCCARPER")
    rsZENCCAR0.ENCCARPEJ = rsADO("ENCCARPEJ")
    rsZENCCAR0.ENCCARBAS = rsADO("ENCCARBAS")
    rsZENCCAR0.ENCCARDDI = rsADO("ENCCARDDI")
    rsZENCCAR0.ENCCARABI = rsADO("ENCCARABI")
    rsZENCCAR0.ENCCARDAR = rsADO("ENCCARDAR")
    rsZENCCAR0.ENCCARDAM = rsADO("ENCCARDAM")
    rsZENCCAR0.ENCCARDAC = rsADO("ENCCARDAC")
    rsZENCCAR0.ENCCARDSU = rsADO("ENCCARDSU")
    rsZENCCAR0.ENCCARDRV = rsADO("ENCCARDRV")
    rsZENCCAR0.ENCCARDRE = rsADO("ENCCARDRE")
    rsZENCCAR0.ENCCARDRC = rsADO("ENCCARDRC")
    rsZENCCAR0.ENCCARCET = rsADO("ENCCARCET")
    rsZENCCAR0.ENCCARCEA = rsADO("ENCCARCEA")
    rsZENCCAR0.ENCCARDRA = rsADO("ENCCARDRA")
    rsZENCCAR0.ENCCARPES = rsADO("ENCCARPES")
    rsZENCCAR0.ENCCARNCH = rsADO("ENCCARNCH")
    rsZENCCAR0.ENCCARRSI = rsADO("ENCCARRSI")
    rsZENCCAR0.ENCCARUEN = rsADO("ENCCARUEN")
    rsZENCCAR0.ENCCARUL1 = rsADO("ENCCARUL1")
    rsZENCCAR0.ENCCARUL2 = rsADO("ENCCARUL2")
    rsZENCCAR0.ENCCARSWI = rsADO("ENCCARSWI")
    rsZENCCAR0.ENCCARDR1 = rsADO("ENCCARDR1")
    rsZENCCAR0.ENCCARDR2 = rsADO("ENCCARDR2")
    rsZENCCAR0.ENCCARDR3 = rsADO("ENCCARDR3")
    Exit Function
Error_Handler:
    rsZENCCAR0_GetBuffer = Error
End Function

Public Sub rsZENCCAR0_Init(rsZENCCAR0 As typeZENCCAR0)
    
    rsZENCCAR0.ENCCARETA = 0
    rsZENCCAR0.ENCCARAGE = 0
    rsZENCCAR0.ENCCARSER = ""
    rsZENCCAR0.ENCCARSSE = ""
    rsZENCCAR0.ENCCARCOP = ""
    rsZENCCAR0.ENCCARDOS = 0
    rsZENCCAR0.ENCCARNAT = ""
    rsZENCCAR0.ENCCAROBJ = ""
    rsZENCCAR0.ENCCARTYD = ""
    rsZENCCAR0.ENCCARTYR = ""
    rsZENCCAR0.ENCCARCPR = ""
    rsZENCCAR0.ENCCARREX = ""
    rsZENCCAR0.ENCCARRCL = ""
    rsZENCCAR0.ENCCARORD = ""
    rsZENCCAR0.ENCCARTIR = ""
    rsZENCCAR0.ENCCARINT = ""
    rsZENCCAR0.ENCCARBES = ""
    rsZENCCAR0.ENCCARBQE = ""
    rsZENCCAR0.ENCCARAVA = ""
    rsZENCCAR0.ENCCARBAV = ""
    rsZENCCAR0.ENCCARCOR = ""
    rsZENCCAR0.ENCCARDPA = ""
    rsZENCCAR0.ENCCARABA = ""
    rsZENCCAR0.ENCCARPPA = ""
    rsZENCCAR0.ENCCARMON = 0
    rsZENCCAR0.ENCCARDEV = ""
    rsZENCCAR0.ENCCARAUT = ""
    rsZENCCAR0.ENCCARTP1 = ""
    rsZENCCAR0.ENCCARMO1 = 0
    rsZENCCAR0.ENCCAREC1 = 0
    rsZENCCAR0.ENCCARPE1 = ""
    rsZENCCAR0.ENCCARNJ1 = ""
    rsZENCCAR0.ENCCARCP1 = ""
    rsZENCCAR0.ENCCARCP2 = ""
    rsZENCCAR0.ENCCARMO2 = 0
    rsZENCCAR0.ENCCAREC2 = 0
    rsZENCCAR0.ENCCARPE2 = ""
    rsZENCCAR0.ENCCARNJ2 = ""
    rsZENCCAR0.ENCCARCP2 = ""
    rsZENCCAR0.ENCCARTP3 = ""
    rsZENCCAR0.ENCCARMO3 = 0
    rsZENCCAR0.ENCCAREC3 = 0
    rsZENCCAR0.ENCCARPE3 = ""
    rsZENCCAR0.ENCCARNJ3 = ""
    rsZENCCAR0.ENCCARCP3 = ""
    rsZENCCAR0.ENCCARFRC = 0
    rsZENCCAR0.ENCCARABF = ""
    rsZENCCAR0.ENCCARTXI = 0
    rsZENCCAR0.ENCCARPER = ""
    rsZENCCAR0.ENCCARPEJ = 0
    rsZENCCAR0.ENCCARBAS = 0
    rsZENCCAR0.ENCCARDDI = 0
    rsZENCCAR0.ENCCARABI = ""
    rsZENCCAR0.ENCCARDAR = 0
    rsZENCCAR0.ENCCARDAM = 0
    rsZENCCAR0.ENCCARDAC = 0
    rsZENCCAR0.ENCCARDSU = 0
    rsZENCCAR0.ENCCARDRV = 0
    rsZENCCAR0.ENCCARDRE = 0
    rsZENCCAR0.ENCCARDRC = 0
    rsZENCCAR0.ENCCARCET = ""
    rsZENCCAR0.ENCCARCEA = ""
    rsZENCCAR0.ENCCARDRA = 0
    rsZENCCAR0.ENCCARPES = 0
    rsZENCCAR0.ENCCARNCH = 0
    rsZENCCAR0.ENCCARRSI = ""
    rsZENCCAR0.ENCCARUEN = 0
    rsZENCCAR0.ENCCARUL1 = 0
    rsZENCCAR0.ENCCARUL2 = 0
    rsZENCCAR0.ENCCARSWI = ""
    rsZENCCAR0.ENCCARDR1 = 0
    rsZENCCAR0.ENCCARDR2 = 0
    rsZENCCAR0.ENCCARDR3 = 0

End Sub

