Attribute VB_Name = "adoZTREOPE0"
'---------------------------------------------------------
Option Explicit
'---------------------------------------------------------
'---------------------------------------------------------
Public Function rsZTREOPE0_PutBuffer(rsADO As ADODB.Recordset, rsZTREOPE0 As typeZTREOPE0)
'---------------------------------------------------------
On Error GoTo Error_Handler
rsZTREOPE0_PutBuffer = Null

rsADO("TREOPEETB") = rsZTREOPE0.TREOPEETB
rsADO("TREOPEAGE") = rsZTREOPE0.TREOPEAGE
rsADO("TREOPESER") = rsZTREOPE0.TREOPESER
rsADO("TREOPESES") = rsZTREOPE0.TREOPESES
rsADO("TREOPEOPR") = rsZTREOPE0.TREOPEOPR
rsADO("TREOPENUM") = rsZTREOPE0.TREOPENUM
rsADO("TREOPENAT") = rsZTREOPE0.TREOPENAT
rsADO("TREOPENEG") = rsZTREOPE0.TREOPENEG
rsADO("TREOPEDIS") = rsZTREOPE0.TREOPEDIS
rsADO("TREOPECLI") = rsZTREOPE0.TREOPECLI
rsADO("TREOPEDEV") = rsZTREOPE0.TREOPEDEV
rsADO("TREOPEMNT") = rsZTREOPE0.TREOPEMNT
rsADO("TREOPEECH") = rsZTREOPE0.TREOPEECH
rsADO("TREOPEREE") = rsZTREOPE0.TREOPEREE
rsADO("TREOPEPRC") = rsZTREOPE0.TREOPEPRC
rsADO("TREOPETIE") = rsZTREOPE0.TREOPETIE
rsADO("TREOPECOU") = rsZTREOPE0.TREOPECOU
rsADO("TREOPEABR") = rsZTREOPE0.TREOPEABR
rsADO("TREOPEDAT") = rsZTREOPE0.TREOPEDAT
rsADO("TREOPEBAS") = rsZTREOPE0.TREOPEBAS
rsADO("TREOPEPRE") = rsZTREOPE0.TREOPEPRE
rsADO("TREOPEPER") = rsZTREOPE0.TREOPEPER
rsADO("TREOPELEV") = rsZTREOPE0.TREOPELEV
rsADO("TREOPEREN") = rsZTREOPE0.TREOPEREN
rsADO("TREOPEROP") = rsZTREOPE0.TREOPEROP
rsADO("TREOPEGAR") = rsZTREOPE0.TREOPEGAR
rsADO("TREOPEPOS") = rsZTREOPE0.TREOPEPOS
rsADO("TREOPEBAN") = rsZTREOPE0.TREOPEBAN
rsADO("TREOPECIV") = rsZTREOPE0.TREOPECIV
rsADO("TREOPEDUR") = rsZTREOPE0.TREOPEDUR
rsADO("TREOPENBP") = rsZTREOPE0.TREOPENBP
rsADO("TREOPECOM") = rsZTREOPE0.TREOPECOM
rsADO("TREOPETRA") = rsZTREOPE0.TREOPETRA
rsADO("TREOPEFRF") = rsZTREOPE0.TREOPEFRF
rsADO("TREOPEREP") = rsZTREOPE0.TREOPEREP
rsADO("TREOPECNF") = rsZTREOPE0.TREOPECNF
rsADO("TREOPEAUT") = rsZTREOPE0.TREOPEAUT
rsADO("TREOPECAM") = rsZTREOPE0.TREOPECAM
rsADO("TREOPEEFF") = rsZTREOPE0.TREOPEEFF
rsADO("TREOPEPAP") = rsZTREOPE0.TREOPEPAP
rsADO("TREOPENAN") = rsZTREOPE0.TREOPENAN
rsADO("TREOPECMT") = rsZTREOPE0.TREOPECMT
rsADO("TREOPEARR") = rsZTREOPE0.TREOPEARR
rsADO("TREOPEETA") = rsZTREOPE0.TREOPEETA
rsADO("TREOPESAI") = rsZTREOPE0.TREOPESAI
rsADO("TREOPEUT1") = rsZTREOPE0.TREOPEUT1
rsADO("TREOPEUT2") = rsZTREOPE0.TREOPEUT2
rsADO("TREOPEORI") = rsZTREOPE0.TREOPEORI
rsADO("TREOPEPTF") = rsZTREOPE0.TREOPEPTF
rsADO("TREOPETIC") = rsZTREOPE0.TREOPETIC
rsADO("TREOPENET") = rsZTREOPE0.TREOPENET
rsADO("TREOPERBT") = rsZTREOPE0.TREOPERBT
rsADO("TREOPEDRB") = rsZTREOPE0.TREOPEDRB
rsADO("TREOPEADO") = rsZTREOPE0.TREOPEADO
Exit Function

Error_Handler:

rsZTREOPE0_PutBuffer = Error

End Function


'---------------------------------------------------------
Public Function adoZTREOPE0_AddNew(rsADO As ADODB.Recordset, rsZTREOPE0 As typeZTREOPE0)
'---------------------------------------------------------
On Error GoTo Error_Handler

adoZTREOPE0_AddNew = Null
rsADO.AddNew
adoZTREOPE0_AddNew = rsZTREOPE0_PutBuffer(rsADO, rsZTREOPE0)
rsADO.Update

Exit Function

Error_Handler:

adoZTREOPE0_AddNew = Error

End Function

